### PR TITLE
CONCF-625 Call processCuratedContentItem for all items, not just articles

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/CONCF-625

Fix for Curated Content items not having `article_local_url` field.

/cc @Warkot @bognix @hakubo

### CODE REVIEW

**Comment by Warkot** [comment]
LGTM :sunglasses: :+1:

**Comment by vforge** [comment]
NICE! :+1:

**Comment by bognix** [comment]
LGTM

**Comment by vforge** [comment]
You found a bug please fill ticket in Jira and put it in your comment.

**Comment by rogatty** [comment]
@v added to comment. Here is the link also:
https://wikia-inc.atlassian.net/browse/CONCF-698

**Comment by vforge** [comment]
:+1:

**Pull request merged**
