### PR TITLE
SUS-3089 |  WikiaNewtalk: use sn_anon_ip column only when handling anons

### PR DESCRIPTION
**Pull request by macbre**
https://wikia-inc.atlassian.net/browse/SUS-3089

A follow-up of #14053. Use `sn_anon_ip` column when querying for and inserting anon data.

Once this goes live, we can drop `sn_user_ip` column.

## Queries

```sql
Query wikicities (DB user: wikia_maint) (20) (master): INSERT /* wfSetWikiaNewtalk CommandLineInc - 6d5f94e8-7ed8-406b-bb4c-f38f2c1ad89a */  INTO `shared_newtalks` (sn_wiki,sn_anon_ip) VALUES ('plpoznan','\0\0 ')
```

```sql
Query wikicities (DB user: wikia_maint) (8) (master): SELECT /* wfGetWikiaNewtalk CommandLineInc - 931e0306-596f-4d63-bee7-9d40176a67ee */  sn_wiki  FROM `shared_newtalks`  WHERE sn_anon_ip = '\0\0 '  LIMIT 255  
Query wikicities (DB user: wikia_maint) (9) (master): SELECT /* wfGetWikiaNewtalk CommandLineInc - 931e0306-596f-4d63-bee7-9d40176a67ee */  city_id,city_title,city_url,city_dbname  FROM `city_list`  WHERE (city_dbname = 'plpoznan') AND city_public = '1'  
```

## New table schema

```sql
CREATE TABLE `shared_newtalks` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `sn_user_id` int(5) unsigned DEFAULT NULL,
  `sn_user_ip` varchar(255) DEFAULT '', -- to be dropped
  `sn_anon_ip` varbinary(16) DEFAULT NULL,
  `sn_wiki` varchar(31) DEFAULT NULL,
  `sn_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_user_ip_wiki` (`sn_user_ip`,`sn_wiki`),
  KEY `idx_user_id_wiki` (`sn_user_id`,`sn_wiki`),
  KEY `idx_anon_ip_wiki` (`sn_anon_ip`,`sn_wiki`)
) ENGINE=InnoDB
```

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [wikia_newtalk.php#L195](https://github.com/Wikia/app/blob/9a0696a86f57587adc9e5b6628347372ed91a406/extensions/wikia/WikiaNewtalk/wikia_newtalk.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [wikia_newtalk.php#L195](https://github.com/Wikia/app/blob/9a0696a86f57587adc9e5b6628347372ed91a406/extensions/wikia/WikiaNewtalk/wikia_newtalk.php#L195): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![INFO][INFO] [wikia_newtalk.php#L143](https://github.com/Wikia/app/blob/9a0696a86f57587adc9e5b6628347372ed91a406/extensions/wikia/WikiaNewtalk/wikia_newtalk.php#L143): Complete the task associated to this "TODO" comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1135)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by mixth-sense** [comment]
Has the new schema been put into some file?

**Review by ghost — COMMENTED** [review]
👍

**Comment by macbre** [comment]
Yes - c6617a58378c385580beea02078028aa8b28fdff

**Pull request merged**
