### PR TITLE
style infobox markup errors

### PR DESCRIPTION
**Pull request by RafLeszczynski**

### CODE REVIEW

**Comment by SebastianMarzjan** [comment]
LGTM. One thing that hit me when going through this was:
**"Which browsers that we support require flexbox mixin?"**

**Comment by RafLeszczynski** [comment]
we still need prefixes for Safari but we will be able to drop them with the next Safari release

**Comment by SebastianMarzjan** [comment]
:+1:

**Comment by RodriGomez** [comment]
Merging to test all error handling tasks in DAT-2839

**Pull request merged**
