### PR TITLE
DAT-3002 Use wfMemcKey instead of manual implode

### PR DESCRIPTION
**Pull request by sebastianmarzjan**
This PR fixes manually constructing of memcache keys that causes crosstalk between staging and production environments for both the global nav and GlobalTitle in general.

### CODE REVIEW

**Comment by SebastianMarzjan** [comment]
@idradm @macbre

**Comment by macbre** [comment]
```php
echo wfMemcKey('Thank', 'you', 'very', 'much');`
```

:smile:

**Comment by idradm** [comment]
EIA :shipit:

**Comment by SebastianMarzjan** [comment]
@ludwikkazmierczak - Merging per our offline conversation

**Pull request merged**
