### PR TITLE
XW-1730 | add local sitemap link to Global Footer API

### PR DESCRIPTION
**Pull request by tomasznapieralski**
https://wikia-inc.atlassian.net/browse/XW-1730

@Wikia/x-wing

### CODE REVIEW

**Comment by tomasznapieralski** [comment]
https://github.com/Wikia/design-system-i18n/pull/11

**Comment by rogatty** [comment]
LGTM

**Comment by kvas-damian** [comment]
LGTM
Before merging please make sure that we download new translations on Mercury.

**Comment by Warkot** [comment]
LGTM

**Comment by Warkot** [comment]
Translations are here: https://github.com/Wikia/design-system-i18n/pull/12.

**Comment by tomasznapieralski** [comment]
https://github.com/Wikia/mercury/pull/2673

**Pull request merged**
