### PR TITLE
Remove config/common extensions.php

### PR DESCRIPTION
**Pull request by ghost**
Sister Wikia/config PR: https://github.com/Wikia/config/pull/2411

### CODE REVIEW

**Comment by ghost** [comment]
http://jenkins.wikia-prod:8080/job/unitTests_php_branches_config/3/
http://jenkins.wikia-prod:8080/job/integrationTests_php_branches_config/2/

**Review by mszabo-wikia — APPROVED** [review]

**Comment by ghost** [comment]
http://jenkins.wikia-prod:8080/job/unitTests_php_branches_config/4/
http://jenkins.wikia-prod:8080/job/integrationTests_php_branches_config/3/

**Review by macbre — APPROVED** [review]

**Comment by ghost** [comment]
Oops, Jenkins went wild and executed tests against `dev`.

http://jenkins.wikia-prod:8080/job/integrationTests_php_branches_config/7/
http://jenkins.wikia-prod:8080/job/unitTests_php_branches_config/4/

All tests pass when executed on a devbox. I have asked @chessky for additional round of Selenium tests (like pre-release tests)

**Comment by ghost** [comment]
Also - this is the first stage of changes, thorough cleanups will follow. There is a few things to optimize, but I want to do it progressively in separate changesets.

**Review by Grunny — APPROVED** [review]

**Comment by ghost** [comment]
http://jenkins.wikia-prod:8080/job/integrationTests_php_branches_config/11/
http://jenkins.wikia-prod:8080/job/unitTests_php_branches_config/5/

all green, also per @chessky , all green in Selenium

**Pull request merged**
