### PR TITLE
SUS-2191: Chat - bump socket.io client version

### PR DESCRIPTION
**Pull request by mszabo-wikia**
Use the latest 2.0.2 client to match server version.

https://wikia-inc.atlassian.net/browse/SUS-2191

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 333 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 328 major
* ![MINOR][MINOR] 1 minor
* ![INFO][INFO] 1 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io.js#L3189](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6628](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6921](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [socket.io.js](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js): File "socket.io.js" has 7253 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS104)
1. ![MAJOR][MAJOR] [socket.io.js#L1](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L1): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR][MAJOR] [socket.io.js#L1](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L1): Remove the declaration of the unused 'module' variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [socket.io.js#L1](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L1): Remove the declaration of the unused 'exports' variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedVariable)
1. ![MAJOR][MAJOR] [socket.io.js#L1](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L1): Remove the unused function parameter "exports". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [socket.io.js#L5](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L5): Remove the unused function parameter "exports". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [socket.io.js#L17](https://github.com/Wikia/app/blob/cd457861edeb09713367cef6f261a45221ebc842/extensions/wikia/Chat2/js/lib/socket.io.js#L17): Remove the unused function parameter "exports". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by mszabo-wikia** [comment]
Criticals are invalid, this is an upstream library.

**Comment by WikiaTech** [comment]
SonarQube analysis reported 391 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 376 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 9 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io.js#L3189](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/lib/socket.io.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6628](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/lib/socket.io.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6921](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/lib/socket.io.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [controllers.js#L31](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR][MAJOR] [controllers.js#L94](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/controllers/controllers.js#L94): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L140](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L140](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L144](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/controllers/controllers.js#L144): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L176](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/controllers/controllers.js#L176): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L216](https://github.com/Wikia/app/blob/f20a90eac91c758fcddc2f3052efd5cd2bf382c6/extensions/wikia/Chat2/js/controllers/controllers.js#L216): Remove the unused function parameter "index". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 391 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 376 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 9 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io.js#L3189](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/lib/socket.io.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6628](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/lib/socket.io.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6921](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/lib/socket.io.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [controllers.js#L31](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/controllers/controllers.js#L31): Remove this logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2228)
1. ![MAJOR][MAJOR] [controllers.js#L94](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/controllers/controllers.js#L94): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L140](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L140](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/controllers/controllers.js#L140): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L144](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/controllers/controllers.js#L144): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L176](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/controllers/controllers.js#L176): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L216](https://github.com/Wikia/app/blob/830dd8c35d466cb85ef65c0878b166b514cb3415/extensions/wikia/Chat2/js/controllers/controllers.js#L216): Remove the unused function parameter "index". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by macbre — APPROVED** [review]

**Pull request merged**
