### PR TITLE
XW-3240 | Don't remove namespace from title

### PR DESCRIPTION
**Pull request by hakubo**

### CODE REVIEW

**Comment by aniaMu** [comment]
Will the change be available also on community.wikia.com? We fetch assets from (not from the specific community) : http://community.wikia.com/extensions/wikia/GameGuides/assets/GameGuidesAssets.json?cb=8064dac1dad4bd8908b3bad98bf98482

**Comment by aniaMu** [comment]
pinging @Wikia/x-wing

**Comment by rogatty** [comment]
@aniaMu yes, I confirmed on a sandbox that it works as expected on `community.wikia.com`.

**Comment by aniaMu** [comment]
Thanks for checking @rogatty! LGTM

**Review by aniaMu — APPROVED** [review]

**Review by kvas-damian — APPROVED** [review]

**Pull request merged**
