### PR TITLE
XW-1304 | Add component info for Mercury

### PR DESCRIPTION
**Pull request by vforge**
http://wikia-inc.atlassian.net/browse/XW-1304

### CODE REVIEW

**Comment by rogatty** [comment]
Does it still work on WikiaMobile? It has too, I think.

**Comment by vforge** [comment]
@rogatty It should work on wikiamobile - some additional attributes were added, WikiaMobile should ignore it anyway.

**Comment by vforge** [comment]
Tests failing aren't connected to the changes.

**Comment by tomasznapieralski** [comment]
lgtm

**Pull request merged**
