### PR TITLE
SUS-2191: Update chat dependencies

### PR DESCRIPTION
**Pull request by mszabo-wikia**
* use socket.io client 2.0.3 to match server version
* build user menu on the client side
* remove relics

Chat PR: https://github.com/Wikia/chat/pull/53
https://wikia-inc.atlassian.net/browse/SUS-2191

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 426 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 407 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io.js#L3189](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/js/lib/socket.io.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6628](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/js/lib/socket.io.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io.js#L6921](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/js/lib/socket.io.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L211](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/Chat_setup.php#L211): Replace or remove this deprecated Wikia::log logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AWikiaLogUsage)
1. ![MAJOR][MAJOR] [controllers.js#L109](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/js/controllers/controllers.js#L109): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L159](https://github.com/Wikia/app/blob/b56fa6ebab5512a3440c2918bc982caf64c23c7d/extensions/wikia/Chat2/js/controllers/controllers.js#L159): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by mszabo-wikia** [comment]
Criticals are in socket.io client library and thus out of scope for fixing.

**Comment by macbre** [comment]
Can we keep the naming convention for `socket.io-1.3.5.js` file so it's easier to find what's the current version?

**Review by macbre — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 426 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 407 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L3189](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6628](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6921](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L211](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/Chat_setup.php#L211): Replace or remove this deprecated Wikia::log logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AWikiaLogUsage)
1. ![MAJOR][MAJOR] [controllers.js#L109](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/js/controllers/controllers.js#L109): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L159](https://github.com/Wikia/app/blob/702734e2179c21edd23a237a15b2a5d58d165a2b/extensions/wikia/Chat2/js/controllers/controllers.js#L159): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by macbre — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 434 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 415 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L3189](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6628](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6921](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L211](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/Chat_setup.php#L211): Replace or remove this deprecated Wikia::log logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AWikiaLogUsage)
1. ![MAJOR][MAJOR] [controllers.js#L109](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/js/controllers/controllers.js#L109): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L159](https://github.com/Wikia/app/blob/b4c50ff7f2513aab09a061ffe61df7798b32b59d/extensions/wikia/Chat2/js/controllers/controllers.js#L159): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 434 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 415 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L3189](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6628](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6921](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L211](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/Chat_setup.php#L211): Replace or remove this deprecated Wikia::log logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AWikiaLogUsage)
1. ![MAJOR][MAJOR] [controllers.js#L109](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/js/controllers/controllers.js#L109): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L159](https://github.com/Wikia/app/blob/31203eeb2d233883eeba00ed6e18666923da281b/extensions/wikia/Chat2/js/controllers/controllers.js#L159): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 434 issues
* ![CRITICAL][CRITICAL] 3 critical
* ![MAJOR][MAJOR] 415 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 13 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L3189](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L3189): TypeError can be thrown as "data" might be null or undefined here. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS2259)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6628](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6628): This loop's stop condition tests "property, members[--length]" but the incrementer updates "hasProperty". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1994)
1. ![CRITICAL][CRITICAL] [socket.io-2.0.3.js#L6921](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/js/lib/socket.io-2.0.3.js#L6921): End this switch case with an unconditional break, continue, return or throw statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANonEmptyCaseWithoutBreak)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L211](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/Chat_setup.php#L211): Replace or remove this deprecated Wikia::log logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AWikiaLogUsage)
1. ![MAJOR][MAJOR] [controllers.js#L109](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/js/controllers/controllers.js#L109): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L159](https://github.com/Wikia/app/blob/844fb1439ea9588af22d49b825e655dbace3b6c3/extensions/wikia/Chat2/js/controllers/controllers.js#L159): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)

[CRITICAL]: https://sonarsource.github.io/sonar-github/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 93 issues
* ![MAJOR][MAJOR] 79 major
* ![MINOR][MINOR] 2 minor
* ![INFO][INFO] 12 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L208](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/Chat_setup.php#L208): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat_setup.php#L211](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/Chat_setup.php#L211): Replace or remove this deprecated Wikia::log logging statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AWikiaLogUsage)
1. ![MAJOR][MAJOR] [controllers.js#L109](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/js/controllers/controllers.js#L109): Add a "default" clause to this "switch" statement. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ASwitchWithoutDefault)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L155](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/js/controllers/controllers.js#L155): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L159](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/js/controllers/controllers.js#L159): Replace "==" with "===". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L191](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/js/controllers/controllers.js#L191): Replace "!=" with "!==". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AEqEqEq)
1. ![MAJOR][MAJOR] [controllers.js#L231](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/js/controllers/controllers.js#L231): Remove the unused function parameter "index". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [controllers.js#L246](https://github.com/Wikia/app/blob/3f09f83550343f96c82f0605b351863b6df08e41/extensions/wikia/Chat2/js/controllers/controllers.js#L246): Restrict what this loop acts on by testing each property. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
