### PR TITLE
SOC-646 | Wall notifications maintenance - fix path

### PR DESCRIPTION
**Pull request by kvas-damian**
https://wikia-inc.atlassian.net/browse/SOC-646

Should be merged with: https://github.com/Wikia/chef-repo/pull/5292

### CODE REVIEW

**Comment by mklucsarits** [comment]
LGTM

**Comment by hakubo** [comment]
LGTM

**Comment by rafalkalinski** [comment]
LGTM

**Comment by dianafa** [comment]
The https://github.com/Wikia/chef-repo/pull/5292 is merged. Is this PR still valid? @kvas-damian

**Comment by hakubo** [comment]
@rafalkalinski Damian is OOO, could you handle that?

**Pull request merged**
