### PR TITLE
SUS-1849: Chat - Remove "Give ChatMod status" option on user menu

### PR DESCRIPTION
**Pull request by mszabo-wikia**
Remove the handling of "Give ChatMod status" option from chat frontend and MediaWiki backend.

https://wikia-inc.atlassian.net/browse/SUS-1849

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 128 issues
* ![MAJOR][MAJOR] 109 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L47](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L47): Remove this unused private "permissionsService" method. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1144)
1. ![MAJOR][MAJOR] [Chat.class.php#L67](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L67): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L70](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L70): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L72](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L72): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L112](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L112): Remove this unused "$cityId" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [Chat.class.php#L264](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L264): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L265](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L265): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L272](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L272): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L274](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L274): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L277](https://github.com/Wikia/app/blob/e10a360a1a3c22d5ea73936b98908fe08ac93848/extensions/wikia/Chat2/Chat.class.php#L277): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 126 issues
* ![MAJOR][MAJOR] 107 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L48](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L48): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L51](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L51): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L53](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L53): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L244](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L244): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L245](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L245): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L252](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L252): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L254](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L254): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L257](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L257): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L265](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L265): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L266](https://github.com/Wikia/app/blob/87fb9160a121cf3b43da575dcd31b18d8b8f2d94/extensions/wikia/Chat2/Chat.class.php#L266): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by macbre — APPROVED** [review]

**Review by sqreek — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 125 issues
* ![MAJOR][MAJOR] 106 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L48](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L48): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L51](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L51): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L53](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L53): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L244](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L244): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L245](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L245): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L252](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L252): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L254](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L254): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L257](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L257): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L265](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L265): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L266](https://github.com/Wikia/app/blob/20241ea5dd1a3185c557b78a7a7a3b7e1eb29075/extensions/wikia/Chat2/Chat.class.php#L266): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 128 issues
* ![MAJOR][MAJOR] 109 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L48](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L48): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L51](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L51): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L53](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L53): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L71](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L71): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR][MAJOR] [Chat.class.php#L248](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L248): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L249](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L249): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L256](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L256): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L258](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L258): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L261](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L261): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L269](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L269): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 129 issues
* ![MAJOR][MAJOR] 110 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 16 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L48](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L48): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L51](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L51): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L53](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L53): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L71](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L71): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR][MAJOR] [Chat.class.php#L248](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L248): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L249](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L249): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L256](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L256): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L258](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L258): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L261](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L261): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L269](https://github.com/Wikia/app/blob/0be06f43c682507d7c922a78a89f9089f8814950/extensions/wikia/Chat2/Chat.class.php#L269): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
