### PR TITLE
SUS-1257 - chat admins blocked by phalanx should not have kick/ban privilege

### PR DESCRIPTION
**Pull request by sqreek**
[SUS-1257](https://wikia-inc.atlassian.net/browse/SUS-1257)

@mix @macbre @TK-999

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 19 issues
* ![MAJOR][MAJOR] 14 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L13](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L13): Class "Chat" has 24 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [Chat.class.php#L67](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L67): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L70](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L70): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L72](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L72): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L90](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L90): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR][MAJOR] [Chat.class.php#L116](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L116): Remove this unused "$cityId" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [Chat.class.php#L366](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L366): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L367](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L367): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L374](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L374): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L376](https://github.com/Wikia/app/blob/2b7fa158ecc7890afa4bc44e02074118285bc178/extensions/wikia/Chat2/Chat.class.php#L376): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by macbre — APPROVED** [review]

**Review by mszabo-wikia — CHANGES_REQUESTED** [review]
I don't think we should introduce tight coupling with Phalanx here. `User::isBlocked` method should check both local blocks and also call Phalanx transparently via hook subscriber.

**Comment by WikiaTech** [comment]
SonarQube analysis reported 19 issues
* ![MAJOR][MAJOR] 14 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L13](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L13): Class "Chat" has 24 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [Chat.class.php#L67](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L67): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L70](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L70): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L72](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L72): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L90](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L90): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR][MAJOR] [Chat.class.php#L116](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L116): Remove this unused "$cityId" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [Chat.class.php#L366](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L366): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L367](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L367): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L374](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L374): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L376](https://github.com/Wikia/app/blob/676269aa7245f45c9a0fceb78825ad0d95610fa8/extensions/wikia/Chat2/Chat.class.php#L376): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by sqreek** [comment]
@TK-999 updated.

**Review by macbre — APPROVED** [review]

**Review by mszabo-wikia — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 19 issues
* ![MAJOR][MAJOR] 14 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [Chat.class.php#L13](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L13): Class "Chat" has 24 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [Chat.class.php#L67](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L67): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L70](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L70): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L72](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L72): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L90](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L90): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR][MAJOR] [Chat.class.php#L116](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L116): Remove this unused "$cityId" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [Chat.class.php#L366](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L366): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L367](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L367): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L374](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L374): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Chat.class.php#L376](https://github.com/Wikia/app/blob/7721ae6e87ae8011cb5f42ede0173a21acaa2cab/extensions/wikia/Chat2/Chat.class.php#L376): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
