### PR TITLE
Remove a Million Lines of Code for Władek!

### PR DESCRIPTION
**Pull request by ghost**
## How to verify whether an extension is in use:
- take a random extension and its directory name, say `FrontBackMatterForcedWikilinks`
- `grep` the config repo for it and if there is no reference, there is a fair chance the extension is not in use
- `grep` the app repo to check whether there is no nasty inclusion elsewhere or whether other extensions do not depend on the one in topic (let's start with the simplest cases: no references)
- use [common sense](http://en.wikipedia.org/wiki/Common_sense)
- one extension per commit
- update the number of removed lines below, because Github lies about it :-)
- link the extension on the list below
- **do make sure unit tests pass and the site still works for anons and logged-in users**
## How to count lines:

```
$ git diff --shortstat dev..dev-remove-million-lines-for-wladek 
9054 files changed, 2167890 deletions(-)
```
## Removed extensions:
- `FrontBackMatterForcedWikilinks` — [link](http://www.mediawiki.org/wiki/Extension:FrontBackMatterForcedWikilinks)
- `ToolserverTools` — seemed remains of something really old
- `AutoProxyBlock` — http://www.mediawiki.org/wiki/Extension:AutoProxyBlock
- `Babel` — http://www.mediawiki.org/wiki/Extension:Babel
- `RdfRedland` — this is really, _really_, **really** old stuff
- `Narayam` — http://www.mediawiki.org/wiki/Extension:Narayam
- `WikimediaMaintenance` — http://www.mediawiki.org/wiki/Extension:WikimediaMaintenance
- `SignupAPI` — http://www.mediawiki.org/wiki/Extension:SignupAPI
- `ImportUsers` — http://www.mediawiki.org/wiki/Extension:ImportUsers
- `DeleteBatch` and `SpecialDeleteBatch` — http://www.mediawiki.org/wiki/Extension:DeleteBatch (plus Wikia's hackaround)
- `uniwiki` — http://www.mediawiki.org/wiki/Category:Uniwiki
- `WikiSync` — http://www.mediawiki.org/wiki/Extension:WikiSync
- `SoundManager2Button` — http://www.mediawiki.org/wiki/Extension:SoundManager2Button
- `Memorize` — http://www.mediawiki.org/wiki/Extension:Memorize
- `Woopra` — http://www.mediawiki.org/wiki/Extension:Woopra
- `MirrorTools` — http://www.mediawiki.org/wiki/Extension:MirrorTools
- `NetworkAuth` — http://www.mediawiki.org/wiki/Extension:NetworkAuth
- `WikiTextLoggedInOut` — http://www.mediawiki.org/wiki/Extension:WikiTextLoggedInOut
- `MakeDBError` — http://www.mediawiki.org/wiki/Extension:MakeDBError
- `WikiBhasha` — http://www.mediawiki.org/wiki/Extension:WikiBhasha
- `Mibbit` — http://www.mediawiki.org/wiki/Extension:Mibbit - obsolete extension
- `freenodeChat` — http://www.mediawiki.org/wiki/Extension:freenodeChat - obsolete extension
- `WebChat` — http://www.mediawiki.org/wiki/Extension:WebChat
- `WindowsAzureSDK` — http://www.mediawiki.org/wiki/Extension:WindowsAzureSDK
- `WindowsAzureStorage` — http://www.mediawiki.org/wiki/Extension:WindowsAzureStorage
- `Lockdown` — http://www.mediawiki.org/wiki/Extension:Lockdown
- `LockDownEnglishPages` — http://www.mediawiki.org/wiki/Extension:LockDownEnglishPages
- `Lockout` — http://mediawiki.org/wiki/Extension:Lockout
- `LogEntry` — https://www.mediawiki.org/wiki/Extension:LogEntry
- `LogoFunctions` — https://www.mediawiki.org/wiki/Extension:LogoFunctions
- `LuaFoo` — https://github.com/themicksa/mediawiki-extensions/tree/master/LuaFoo
- `MagicNoNumberedHeadings` — https://www.mediawiki.org/wiki/Extension:MagicNoNumberedHeadings
- `MakeBot` — http://www.mediawiki.org/wiki/Extension:MakeBot
- `Makesysop` — http://www.mediawiki.org/wiki/Extension:Makesysop

### CODE REVIEW

**Comment by wladekb** [comment]
2 011 968 fewer lines

**Comment by wladekb** [comment]
FYI   5 261 632 still waiting to be verified

**Comment by michalroszka** [comment]
Hey, you cannot remove lines in your own honor! :-)

**Comment by wladekb** [comment]
Fixed. My changes disappeared :-)

**Comment by pchojnacki** [comment]
I :heart:  this PR

**Comment by owend** [comment]
Not sure about MessageOverrides extension... maybe check with @lgarczewski ?

**Comment by wladekb** [comment]
I couldn't find any reference to MessageOverrides neither in app nor in config.

**Comment by owend** [comment]
BOOM  :boom:

**Pull request merged**
