### PR TITLE
ADEN-7180 Fixes opt-in context

### PR DESCRIPTION
**Pull request by leshniak**

### CODE REVIEW

**Comment by fraszczakszymon** [comment]
`git grep 'trackingOptOut' | grep -v build`
There is another ticket for clean up: ADEN-7177 but there are some not needed lines (AdEngine/src/context.js)

**Comment by nandy-andy** [comment]
@fraszczakszymon what other ticket did you have in mind in previous comment? We might want to update it with things left to clean up:
* usage of the out-dated module in analytics providers,
* loading the module by ResourceLoader and AssetManager,
* the references in `AdEngine/src/context.js`,
* the references in unit tests.

If it's safer not to clean above within this PR - it LGTM ;-)

**Comment by fraszczakszymon** [comment]
@leshniak what about `extensions/wikia/AdEngine/src/context.js`

**Comment by nandy-andy** [comment]
It's [ADEN-7177](https://wikia-inc.atlassian.net/browse/ADEN-7177) where we can update the description with things left to clean! Apparently, I became blind while reading @fraszczakszymon's comment yesterday ;)

**Review by fraszczakszymon — APPROVED** [review]

**Pull request merged**
