### PR TITLE
Lazily Inject PreferencePersistenceMySQL

### PR DESCRIPTION
**Pull request by nmonterroso**
@Wikia/services-team 
https://wikia-inc.atlassian.net/browse/SERVICES-575

We were always instantiating `PreferencePersistenceMySQL` and creating database connections even if they weren't used. This change makes it so that `PreferencePersistenceMySQL` is only created if it's used, using [lazy injection](http://php-di.org/doc/lazy-injection.html) in the dependency injection framework. 

The diff here is pretty huge, but it's mostly new dependency code being added. The actual changes for lazy injection is in 33ab104

### CODE REVIEW

**Comment by drsnyder** [comment]
Are the large number of files coming from the `proxy-manager`? Github isn't able to display the diff.

**Comment by nmonterroso** [comment]
Yeah, `proxy-manager` and its dependencies. The actual changes on our side are in 33ab104

**Comment by drsnyder** [comment]
Haha, all of that for 3 lines.

Is there an additional build step required or does the DI framework do that when the files are autoloaded?

**Comment by nmonterroso** [comment]
No build step required, the DI framework takes care of the magic

**Comment by drsnyder** [comment]
lgtm

**Comment by ArturKlajnerok** [comment]
Lgtm :+1:

**Pull request merged**
