### PR TITLE
CAKE-5599 | Add translations

### PR DESCRIPTION
**Pull request by JoshuaRogan**
@Wikia/cake I would like a triple verification of the copy/paste for this PR so everything launches correctly. Please use [zeplin](https://app.zeplin.io/project/5c34f8570b5f05bdc9806cb9/screen/5e7512258651056664fab9d2) to match the translations and [this sheet](https://docs.google.com/spreadsheets/d/1u_jo4rQSmSo1qNrUM-tijTom-B9OK_sQGtT9o_zT000/edit#gid=2026655550) (look for my name in the notes) to match the links. 

### Translations are correct heading/subheading
- [x] UK (GB) verified
- [x] IE verified
- [x] ES verified
- [x] IT verified
- [x] DE verified

### Desktop links are correct
- [x] UK (GB) verified
- [x] IE verified
- [x] ES verified
- [x] IT verified
- [x] DE verified

### Translations are correct heading/subheading
- [x] UK (GB) verified
- [x] IE verified
- [x] ES verified
- [x] IT verified
- [x] DE verified

### Desktop links are correct
- [x] UK (GB) verified
- [x] IE verified
- [x] ES verified
- [x] IT verified
- [x] DE verified

### Translations are correct heading/subheading
- [x] UK (GB) verified
- [x] IE verified
- [x] ES verified
- [x] IT verified
- [x] DE verified

### Desktop links are correct
- [x] UK (GB) verified
- [x] IE verified
- [x] ES verified
- [x] IT verified
- [x] DE verified

### CODE REVIEW

**Comment by cschucode** [comment]
ES link looks off. This is from the spreadsheet: 
https://disneyplus.bn5x.net/c/1947570/772703/9358?subId1=generic-es&subId2=preorder&subId3=ad-fandom&sharedid=facebook

**Comment by JoshuaRogan** [comment]
@cschucode 

> ES link looks off. This is from the spreadsheet:
> https://disneyplus.bn5x.net/c/1947570/772703/9358?subId1=generic-es&subId2=preorder&subId3=ad-fandom&sharedid=facebook

That's the preorder link and for facebook.

**Comment by unijuglr** [comment]
The mockup has the UK text as initial cap on every word, but the text in the config does not match that. I assume this has to be done with the text in the config, as other languages do not use initial caps, so it can't be a font transition.

**Comment by unijuglr** [comment]
My previous comment goes to both IE and GB

**Comment by unijuglr** [comment]
Sorry Josh, missed one, for GB: All In One place

**Pull request merged**
