### PR TITLE
SER-418 set default swagger timeout to 5s

### PR DESCRIPTION
**Pull request by kpiotrowski**
ticket: https://wikia-inc.atlassian.net/browse/SER-418

ping: @Wikia/services-team

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 8 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. CRITICAL [Configuration.php#L87](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L87): Remove this hard-coded password. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2068)
2. MAJOR [Configuration.php#L49](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L49): Class "Configuration" has 31 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
3. MAJOR [Configuration.php#L492](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L492): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
4. MAJOR [Configuration.php#L493](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L493): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
5. MAJOR [Configuration.php#L496](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L496): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
6. MAJOR [Configuration.php#L508](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L508): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
7. MAJOR [Configuration.php#L522](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L522): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
8. MINOR [Configuration.php#L522](https://github.com/Wikia/app/blob/02bd750df2e1e3d01524d559d9b458c4a5dc3676/lib/Swagger/src/Configuration.php#L522): Immediately return this expression instead of assigning it to the temporary variable "$report". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1488)

**Comment by kpiotrowski** [comment]
ping @harnash

**Comment by kpiotrowski** [comment]
Does it mean LGTM? :)

**Comment by tmszdmsk** [comment]
👍

**Comment by harnash** [comment]
LGTM

**Comment by sqreek** [comment]
tested with fake timeouting service

**Pull request merged**
