### PR TITLE
CONCF-558 move css rule to file which is used on breakpoints

### PR DESCRIPTION
**Pull request by bognix**
https://wikia-inc.atlassian.net/browse/CONCF-558

ping @rogatty @hakubo 

@gabrys - this rule is used to override rule which is added here: https://github.com/Wikia/app/blob/dev/skins/oasis/css/core/page.scss#L87-L90
Maybe we don't need this rule from page.scss in the first place?

### CODE REVIEW

**Comment by rogatty** [comment]
The code LGTM but I have no idea if it can break something.

**Comment by bognix** [comment]
@rogatty - it shouldn't after second commit. Now we only target responsive and breakpoints based versions of oasis.

**Comment by gabrys** [comment]
We still give the german wikis oasis-fluid treatment. And they have the 
prefooter ads (one of them in fact). The anticipated date of converting 
them to breakpoints is 1st July according to Esteban.

**Comment by bognix** [comment]
@gabrys - I know, that's why this rule is applied to both old responsive and new breakpoints based layouts.

**Comment by rogatty** [comment]
@gabrys is comment from @bognix satisfying for you? Does it look good to you?

**Comment by nandy-andy** [comment]
I'm think if it would be a good practice to add a follow-up ticket to clean this code after we release Oasis breakpoints on German wikias and `//TODO` comments with the ticket number here. Thanks to that we'd gain even more red numbers in next PR connected to the follow-up ticket :smile_cat: What do you think about it? :japanese_ogre:

**Comment by hakubo** [comment]
LGTM

**Comment by bognix** [comment]
@nandy-andy - added comments as you suggested. Although best idea would be to remove this rule: https://github.com/Wikia/app/blob/dev/skins/oasis/css/core/page.scss#L87-L90

do you know if it still needed? from what I know we don't display prefooters on wikia.com and subpages and this is the only page where grid is enabled.

**Comment by nandy-andy** [comment]
@bognix those lines were added in 2010 from what I can check. It was before I worked here ;) I removed them in my devbox and only spacing around pre-footer ads changed - and does not look bad. I'd remove them if it causes troubles or the code is less cleaner with them :japanese_ogre:

**Comment by bognix** [comment]
@nandy-andy I created a ticket to take care of wikia grid skin. If it is solved then those lines won't matter anymore and will be removed.

**Comment by nandy-andy** [comment]
Thanks for taking care of it! :smile_cat:

**Pull request merged**
