### PR TITLE
CE-3124: Publish template after forced modal

### PR DESCRIPTION
**Pull request by lukaszkonieczny**
Publish template after forced modal

### CODE REVIEW

**Comment by adamkarminski** [comment]
LGTM, since `$('#wpSave').click()` is a pattern that we use for publishing from preview as well. :)

**Comment by kamilkoterba** [comment]
Probably $('#editform').submit() is better idea.

**Comment by kamilkoterba** [comment]
In general that should work although I don't feel like publishing is responsibility of TemplateClassificationModal.js

Plus it won't work for ACE editor which is not shown for unclassified templates right now but it's something we should be aware. 

(edit)
Actually just found out that $('#wpSave') button is common for ACE and Source so it will work for both. Let's leave it like this I suggest.

**Comment by kamilkoterba** [comment]
LGTM

**Comment by azarek** [comment]
Testing done! LGTM

**Comment by adamkarminski** [comment]
@lukaszkonieczny @kamilkoterba - LGTM, but please resolve conflicts before merge.

**Pull request merged**
