### PR TITLE
IW-1213 | Moving articlePath into common WikiVariables

### PR DESCRIPTION
**Pull request by bkoval**
@Wikia/iwing

### CODE REVIEW

**Comment by rybmat** [comment]
https://github.com/Wikia/app/pull/16296/files#diff-21bab35e67dfc42ffdd18afcf2c13b6cR187 we should get rid of it as well

**Review by rybmat — CHANGES_REQUESTED** [review]
https://github.com/Wikia/app/pull/16296/files#diff-21bab35e67dfc42ffdd18afcf2c13b6cR187 we should get rid of it as well

**Comment by Grunny** [comment]
We're doing this as well in https://github.com/Wikia/app/pull/16258 :)

**Comment by rybmat** [comment]
closing as duplicate of #16258

**Pull request closed without merging**
