### PR TITLE
CONCF-900 | remove wgEnableCuratedContentUnauthorizedSave

### PR DESCRIPTION
**Pull request by tomasznapieralski**
https://wikia-inc.atlassian.net/browse/CONCF-900

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by vforge** [comment]
LGTM

**Comment by justnpT** [comment]
Merged
Unit test failure reason is virtual machine issue

**Comment by justnpT** [comment]
Merged
Unit test failure reason is virtual machine issue

**Comment by justnpT** [comment]
Unit test failure reason is virtual machine issue

**Pull request merged**
