### PR TITLE
Escape abstract and description fields to prevent from XSS attack

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/HG-564

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by gabrys** [comment]
Actually I don't like it this way. Why API would return stuff HTML encoded?

**Comment by hakubo** [comment]
To optimise for main use case I think.

**Comment by gabrys** [comment]
Well, not really. It the issue in front of the API (the data in not escaped when transferring to browser as part of HTML) and you're fixing this by changing what API returns. The app should escape the data, not the API. If the API is used for displaying the abstract to a text file or console, you would need to always de-escape what API returns. Seems counter-intuitive to me.

**Comment by hakubo** [comment]
I partially agree with your point Rychu but is dumping the data to a text file our main use case?

**Comment by gabrys** [comment]
Nope, but in general:

* an API should be universal unless there are good reason for that not too
* an app should be safe even if API returns unescaped HTML ;-)

The most important part is we eliminated the XSS, so thumbs up for that!

**Pull request merged**
