### PR TITLE
ADEN-6189 pubMatic prebid.js adapter

### PR DESCRIPTION
**Pull request by dianafa**
https://wikia-inc.atlassian.net/browse/ADEN-6189

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 13 issues
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$title". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$article". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$output". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$user". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$wiki". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L137](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L137): Remove the unused function parameter "$scripts". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L138](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L138): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L212](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L212): Remove the unused function parameter "$skin". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$jsExtensionPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/35899926ab60e992255dadf2cd7727e3fd801933/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$scssPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 13 issues
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$title". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$article". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$output". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$user". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$wiki". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L137](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L137): Remove the unused function parameter "$scripts". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L138](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L138): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L212](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L212): Remove the unused function parameter "$skin". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$jsExtensionPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/62766708fafdbb6211492a95dbe87e8b4418ae18/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$scssPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 13 issues
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$title". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$article". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$output". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$user". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$wiki". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L137](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L137): Remove the unused function parameter "$scripts". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L138](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L138): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L212](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L212): Remove the unused function parameter "$skin". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$jsExtensionPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/96a58600f2b073415e221922d5b7152087d2d50e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$scssPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by fraszczakszymon — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 12 issues
* ![MAJOR][MAJOR] 9 major
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$title". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$article". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$output". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$user". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$wiki". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L137](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L137): Remove the unused function parameter "$scripts". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L212](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L212): Remove the unused function parameter "$skin". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$jsExtensionPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$scssPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![INFO][INFO] [AdEngine2Hooks.class.php#L21](https://github.com/Wikia/app/blob/8c86c0e8753a494bccce9f920744a06d69884c1e/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L21): Complete the task associated to this "TODO" comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1135)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by fraszczakszymon — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 12 issues
* ![MAJOR][MAJOR] 9 major
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$title". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$article". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$output". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$user". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$wiki". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L137](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L137): Remove the unused function parameter "$scripts". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L212](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L212): Remove the unused function parameter "$skin". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$jsExtensionPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$scssPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![INFO][INFO] [AdEngine2Hooks.class.php#L21](https://github.com/Wikia/app/blob/3f49f80f23d2c560c8113acca58f50014ca30154/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L21): Complete the task associated to this "TODO" comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1135)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by fraszczakszymon — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 15 issues
* ![MAJOR][MAJOR] 12 major
* ![INFO][INFO] 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$title". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$article". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$output". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$user". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L18](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L18): Remove the unused function parameter "$wiki". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L137](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L137): Remove the unused function parameter "$scripts". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L212](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L212): Remove the unused function parameter "$skin". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$jsExtensionPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [AdEngine2Hooks.class.php#L236](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/AdEngine2Hooks.class.php#L236): Remove the unused function parameter "$scssPackages". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [adInfoTracker.js#L15](https://github.com/Wikia/app/blob/2fc29a6314c3a574effe0cb0bc4a228d53b376ee/extensions/wikia/AdEngine/js/tracking/adInfoTracker.js#L15): Function has 5 parameters which is greater than 4 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-js-rules%3AAmdExcludedFunctionParameterLimit)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Pull request merged**
