### PR TITLE
Revert "Revert "SUS-519 Remove Hero Module code""

### PR DESCRIPTION
**Pull request by macbre**
Reverts Wikia/app#11796

https://wikia-inc.atlassian.net/browse/SUS-519

@mixth-sense / @TK-999

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/663ae3916a21e17057f46ce44017033e950c84c5/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/663ae3916a21e17057f46ce44017033e950c84c5/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/663ae3916a21e17057f46ce44017033e950c84c5/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L69](https://github.com/Wikia/app/blob/663ae3916a21e17057f46ce44017033e950c84c5/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L69): Define a constant instead of duplicating this literal "normal" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L69](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L69): Define a constant instead of duplicating this literal "normal" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L69](https://github.com/Wikia/app/blob/f0fbcb9e32018b432bd02a10f03aa7145da7ff8c/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L69): Define a constant instead of duplicating this literal "normal" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/fc8f3876c43f1ce4ac483da00727e472b5997e43/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/fc8f3876c43f1ce4ac483da00727e472b5997e43/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/fc8f3876c43f1ce4ac483da00727e472b5997e43/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L69](https://github.com/Wikia/app/blob/fc8f3876c43f1ce4ac483da00727e472b5997e43/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L69): Define a constant instead of duplicating this literal "normal" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 25 issues
* MAJOR 4 major
* MINOR 18 minor
* INFO 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [PermissionsConfigurationImpl.php#L437](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L437): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L439](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L439): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L441](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L441): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L443](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L443): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L69](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L69): Define a constant instead of duplicating this literal "normal" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L26](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L26): Define a constant instead of duplicating this literal "content-reviewer" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L28](https://github.com/Wikia/app/blob/b6b39466299242b5889257088e0d92a82b80ca86/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L28): Define a constant instead of duplicating this literal "helper" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 29 issues
* MAJOR 8 major
* MINOR 18 minor
* INFO 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ve.ui.WikiaFocusWidget.js#L14](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L14): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. MAJOR [ve.ui.WikiaFocusWidget.js#L91](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L91): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)
1. MAJOR [ve.ui.WikiaFocusWidget.js#L105](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L105): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)
1. MAJOR [ve.ui.WikiaFocusWidget.js#L138](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L138): Restrict what this loop acts on by testing each property. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)
1. MAJOR [PermissionsConfigurationImpl.php#L437](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L437): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L439](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L439): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L441](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L441): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L443](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L443): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/b2662ef4731b4d7a6082c2db5658a0e5fff04ebb/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 29 issues
* MAJOR 8 major
* MINOR 18 minor
* INFO 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [ve.ui.WikiaFocusWidget.js#L14](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L14): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. MAJOR [ve.ui.WikiaFocusWidget.js#L91](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L91): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)
1. MAJOR [ve.ui.WikiaFocusWidget.js#L105](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L105): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACommentedCode)
1. MAJOR [ve.ui.WikiaFocusWidget.js#L138](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/extensions/VisualEditor/wikia/modules/ve/ui/widgets/ve.ui.WikiaFocusWidget.js#L138): Restrict what this loop acts on by testing each property. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)
1. MAJOR [PermissionsConfigurationImpl.php#L437](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L437): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L439](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L439): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L441](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L441): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L443](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L443): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/cba3e507eb8cba126bc7efcd2560f4ff341a8ce8/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)

**Review by ghost — APPROVED** [review]

**Pull request merged**
