### PR TITLE
SOC-3179

### PR DESCRIPTION
**Pull request by kerriamber**
ping @armonr @jsutterfield

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 35 issues
* MAJOR 10 major
* MINOR 23 minor
* INFO 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [SpecialContact.body.php#L72](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L72): The Cyclomatic Complexity of this function "execute" is 33 which is greater than 20 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1541)
1. MAJOR [SpecialContact.body.php#L72](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L72): This function "execute" has 174 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS138)
1. MAJOR [SpecialContact.body.php#L140](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L140): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. MAJOR [SpecialContact.body.php#L250](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L250): The Cyclomatic Complexity of this function "processCreation" is 23 which is greater than 20 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1541)
1. MAJOR [SpecialContact.body.php#L424](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L424): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. MAJOR [SpecialContact.body.php#L635](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L635): Remove this unused "$titleObj" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. MAJOR [SpecialContact.body.php#L691](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L691): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. MAJOR [SpecialContact.body.php#L693](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L693): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. MAJOR [SpecialContact.body.php#L696](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L696): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
1. MAJOR [SpecialContact.body.php#L718](https://github.com/Wikia/app/blob/4e6b12c492f698aefd6272179e79866bdac3df52/extensions/wikia/SpecialContact2/SpecialContact.body.php#L718): Reduce the number of returns of this function 5, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 50 issues
- MAJOR 17 major
- MINOR 27 minor
- INFO 6 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MAJOR [SpecialContact.body.php#L72](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L72): The Cyclomatic Complexity of this function "execute" is 33 which is greater than 20 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1541)
2. MAJOR [SpecialContact.body.php#L72](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L72): This function "execute" has 174 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS138)
3. MAJOR [SpecialContact.body.php#L140](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L140): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
4. MAJOR [SpecialContact.body.php#L250](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L250): The Cyclomatic Complexity of this function "processCreation" is 23 which is greater than 20 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1541)
5. MAJOR [SpecialContact.body.php#L424](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L424): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
6. MAJOR [SpecialContact.body.php#L635](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L635): Remove this unused "$titleObj" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
7. MAJOR [SpecialContact.body.php#L691](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L691): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
8. MAJOR [SpecialContact.body.php#L693](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L693): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
9. MAJOR [SpecialContact.body.php#L696](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L696): Refactor this code to not nest more than 4 "if", "for", "while", "switch" and "try" statements. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS134)
10. MAJOR [SpecialContact.body.php#L718](https://github.com/Wikia/app/blob/50d784aac73792632fe12c16bef96815176bfb98/extensions/wikia/SpecialContact2/SpecialContact.body.php#L718): Reduce the number of returns of this function 5, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)

**Comment by jsutterfield** [comment]
LGTM! Just please make sure to include the jira ticket in the PR description.

**Comment by armonr** [comment]
:shipit:

**Pull request merged**
