### PR TITLE
PLATFORM-2466 fixing bad header forwarding

### PR DESCRIPTION
**Pull request by pgrabowski-wikia**
https://wikia-inc.atlassian.net/browse/PLATFORM-2466

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [WikiaTracer.php#L7](https://github.com/Wikia/app/blob/9658382230919bd6a66ddf88712b7e13a9da4b1b/lib/Wikia/src/Tracer/WikiaTracer.php#L7): Class "WikiaTracer" has 29 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [WikiaTracer.php#L371](https://github.com/Wikia/app/blob/9658382230919bd6a66ddf88712b7e13a9da4b1b/lib/Wikia/src/Tracer/WikiaTracer.php#L371): Remove the unused function parameter "$cmd". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. MAJOR [WikiaTracer.php#L392](https://github.com/Wikia/app/blob/9658382230919bd6a66ddf88712b7e13a9da4b1b/lib/Wikia/src/Tracer/WikiaTracer.php#L392): Remove the unused function parameter "$method". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [WikiaTracer.php#L7](https://github.com/Wikia/app/blob/b1147834c65815e14025ef35d8e55ffbc5bc65fb/lib/Wikia/src/Tracer/WikiaTracer.php#L7): Class "WikiaTracer" has 29 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [WikiaTracer.php#L370](https://github.com/Wikia/app/blob/b1147834c65815e14025ef35d8e55ffbc5bc65fb/lib/Wikia/src/Tracer/WikiaTracer.php#L370): Remove the unused function parameter "$cmd". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. MAJOR [WikiaTracer.php#L391](https://github.com/Wikia/app/blob/b1147834c65815e14025ef35d8e55ffbc5bc65fb/lib/Wikia/src/Tracer/WikiaTracer.php#L391): Remove the unused function parameter "$method". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 3 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MAJOR [WikiaTracer.php#L7](https://github.com/Wikia/app/blob/07cd89abce9a1a8aa23f655f508511eac535ad02/lib/Wikia/src/Tracer/WikiaTracer.php#L7): Class "WikiaTracer" has 29 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
2. MAJOR [WikiaTracer.php#L371](https://github.com/Wikia/app/blob/07cd89abce9a1a8aa23f655f508511eac535ad02/lib/Wikia/src/Tracer/WikiaTracer.php#L371): Remove the unused function parameter "$cmd". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
3. MAJOR [WikiaTracer.php#L392](https://github.com/Wikia/app/blob/07cd89abce9a1a8aa23f655f508511eac535ad02/lib/Wikia/src/Tracer/WikiaTracer.php#L392): Remove the unused function parameter "$method". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)

**Review by Grunny — APPROVED** [review]
LGTM.

**Pull request merged**
