### PR TITLE
SUS-809: LocalFile - get username from user id

### PR DESCRIPTION
**Pull request by saipetch**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 106 issues
* MAJOR 15 major
* MINOR 54 minor
* INFO 37 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [LocalFile.php](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php): File "LocalFile.php" has 2565 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS104)
1. MAJOR [LocalFile.php#L31](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L31): Class "LocalFile" has 59 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
1. MAJOR [LocalFile.php#L626](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L626): Remove this commented out code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS125)
1. MAJOR [LocalFile.php#L967](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L967): Merge this if statement with the enclosing one. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1066)
1. MAJOR [LocalFile.php#L999](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L999): This function "recordUpload2" has 227 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS138)
1. MAJOR [LocalFile.php#L1067](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L1067): Remove this commented out code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS125)
1. MAJOR [LocalFile.php#L1489](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L1489): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [LocalFile.php#L1491](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L1491): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [LocalFile.php#L1835](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L1835): Remove this unused "$deleteCurrent" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
1. MAJOR [LocalFile.php#L1923](https://github.com/Wikia/app/blob/5691076d18e29d985dde57f62e28392c2a2d97bd/includes/filerepo/file/LocalFile.php#L1923): Remove this unused "$dest" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 107 issues
- MAJOR 15 major
- MINOR 55 minor
- INFO 37 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MAJOR [LocalFile.php](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php): File "LocalFile.php" has 2565 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS104)
2. MAJOR [LocalFile.php#L31](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L31): Class "LocalFile" has 59 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
3. MAJOR [LocalFile.php#L626](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L626): Remove this commented out code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS125)
4. MAJOR [LocalFile.php#L967](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L967): Merge this if statement with the enclosing one. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1066)
5. MAJOR [LocalFile.php#L999](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L999): This function "recordUpload2" has 227 lines, which is greater than the 150 lines authorized. Split it into smaller functions. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS138)
6. MAJOR [LocalFile.php#L1067](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L1067): Remove this commented out code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS125)
7. MAJOR [LocalFile.php#L1489](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L1489): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
8. MAJOR [LocalFile.php#L1491](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L1491): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
9. MAJOR [LocalFile.php#L1835](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L1835): Remove this unused "$deleteCurrent" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
10. MAJOR [LocalFile.php#L1923](https://github.com/Wikia/app/blob/6434730dc637d10022c40ede6da6ba30ce0797f2/includes/filerepo/file/LocalFile.php#L1923): Remove this unused "$dest" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)

**Comment by pwojcik86** [comment]
I updated this PR to use the new username lookup function

**Comment by jcellary** [comment]
LGTM

**Pull request merged**
