### PR TITLE
XW-3477 | remove focus widget

### PR DESCRIPTION
**Pull request by latata**
https://wikia-inc.atlassian.net/browse/XW-3300

VE FocusWidget breaks VE after enabling new community header (there is no more `#localNavigation` element in DOM). We can remove it as it was hidden by `display: none !important;` in `breakpoints-layout.scss`

@Wikia/x-wing

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 27 issues
* ![MAJOR][MAJOR] 22 major
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ve.ui.Surface.js#L22](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/lib/ve/src/ui/ve.ui.Surface.js#L22): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR][MAJOR] [ve.ui.Surface.js#L320](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/lib/ve/src/ui/ve.ui.Surface.js#L320): Merge this if statement with the nested one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACollapsibleIfStatements)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js): File "ve.init.mw.ViewPageTarget.js" has 1819 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS104)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L18](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L18): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L68](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L68): Restrict what this loop acts on by testing each property. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L111](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L111): Take the required action to fix the issue indicated by this comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L201](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L201): Take the required action to fix the issue indicated by this comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L415](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L415): Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L543](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L543): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L562](https://github.com/Wikia/app/blob/8d6c3c29ccf4ec385fc09440cd88bd505b270233/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L562): Function has 7 parameters which is greater than 4 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 27 issues
* ![MAJOR][MAJOR] 22 major
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ve.ui.Surface.js#L22](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/lib/ve/src/ui/ve.ui.Surface.js#L22): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR][MAJOR] [ve.ui.Surface.js#L320](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/lib/ve/src/ui/ve.ui.Surface.js#L320): Merge this if statement with the nested one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACollapsibleIfStatements)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js): File "ve.init.mw.ViewPageTarget.js" has 1819 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS104)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L18](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L18): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L68](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L68): Restrict what this loop acts on by testing each property. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L111](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L111): Take the required action to fix the issue indicated by this comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L201](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L201): Take the required action to fix the issue indicated by this comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L415](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L415): Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L543](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L543): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L562](https://github.com/Wikia/app/blob/a0c15208d5a2d5c3aa8369e82669a80fd19e57c5/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L562): Function has 7 parameters which is greater than 4 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 27 issues
* ![MAJOR][MAJOR] 22 major
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [ve.ui.Surface.js#L22](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/lib/ve/src/ui/ve.ui.Surface.js#L22): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR][MAJOR] [ve.ui.Surface.js#L320](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/lib/ve/src/ui/ve.ui.Surface.js#L320): Merge this if statement with the nested one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ACollapsibleIfStatements)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js): File "ve.init.mw.ViewPageTarget.js" has 1819 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS104)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L18](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L18): Make this function anonymous by removing its name: 'function() {...}'. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3ANamedFunctionExpression)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L68](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L68): Restrict what this loop acts on by testing each property. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AForIn)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L111](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L111): Take the required action to fix the issue indicated by this comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L201](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L201): Take the required action to fix the issue indicated by this comment. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1134)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L415](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L415): Reduce the number of conditional operators (4) used in the expression (maximum allowed 3). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L543](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L543): Reduce the number of conditional operators (5) used in the expression (maximum allowed 3). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AS1067)
1. ![MAJOR][MAJOR] [ve.init.mw.ViewPageTarget.js#L562](https://github.com/Wikia/app/blob/5ca290ba737bbc25039e58061df5baad53adab12/extensions/VisualEditor/modules/ve-mw/init/targets/ve.init.mw.ViewPageTarget.js#L562): Function has 7 parameters which is greater than 4 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Review by rybmat — APPROVED** [review]
If does not break anything then lgtm

**Review by rogatty — APPROVED** [review]

**Pull request merged**
