### PR TITLE
SUS-84: improve special characters support in Lightbox share feature

### PR DESCRIPTION
**Pull request by macbre**
[SUS-84](https://wikia-inc.atlassian.net/browse/SUS-84)

`data-*-name` attributes are not URI encoded (like `data-*-key` ones)

And now we get a proper handling of special characters like quotation marks.

Avoid double encoding in `WikiaPhotoGallery` and `MediaTransformOutput` - HTML and XML helpers do perform HTML encoding internally. Just one encoding is simply enough :)

@Wikia/sustaining-team

### CODE REVIEW

**Comment by macbre** [comment]
Tests do pass - http://qa-s2.wikia-prod:8080/job/unitTests_js_branches/24726/ & http://qa-s2.wikia-prod:8080/job/unitTests_php_branches/27382/

**Comment by kvas-damian** [comment]
LGTM

**Comment by macbre** [comment]
```
PhalanxServiceTest::testPhalanxServiceMethod
Exception: Can't connect to phalanx service on http://phalanx.service.consul:4666
```

Unrelated to changes in this pull request.

**Comment by wladekb** [comment]
Anything happening here?

**Comment by ghost** [comment]
Sort of.

**Pull request closed without merging**
