### PR TITLE
(CE-2970) Add logging of classification actions to Special:Log

### PR DESCRIPTION
**Pull request by adamkarminski**
The copy is approved by Trevor - we use only 1 message and if a template was not classified before we just display a change from Unknown.

Side note: From a quick test that I ran it seems that adding an additional request to TCS for the oldType and adding an entry to logs does not make the response time of the API significantly longer.

/cc: @Wikia/community-engineering

### CODE REVIEW

**Comment by kamilkoterba** [comment]
LGTM

**Comment by azarek** [comment]
Testing done! LGTM

**Comment by Grunny** [comment]
To define this properly on Special:Log so it can be filtered, the following needs to be added:

``` php
$wgLogTypes[] = 'templateclassification';
```

By default, the log page title will use `log-name-templateclassification` and `log-description-templateclassification` as the message keys for the filtered log page. These keys can be overridden, however.

**Comment by azarek** [comment]
Filtration works!

**Comment by Grunny** [comment]
:+1:

**Pull request merged**
