### PR TITLE
PLATFORM-1836 Disable Special:PasswordReset for real

### PR DESCRIPTION
**Pull request by RafalWilinski**
https://wikia-inc.atlassian.net/browse/PLATFORM-1836

After disabling this special page it's time to remove it for real but let's wait till real end of the week.

/cc @jcellary.

### CODE REVIEW

**Comment by RafalWilinski** [comment]
@jcellary I think it's good time to check it and give it a go. As far as I know you're not much experienced in MW so should I find someone else to review this?

**Comment by RafalWilinski** [comment]
cc @macbre @wladekb

**Comment by RafalWilinski** [comment]
Could someone verify if I can remove these also? https://github.com/Wikia/app/blob/dev/maintenance/language/messages.inc#L481-L498

**Comment by RafalWilinski** [comment]
From my understanding of the topic purging these translations (from MessagesXX.php files) _shouldn't_ affect something else than `Special:PasswordReset` which is also going to be removed.

**Comment by wladekb** [comment]
lgtm,
I think you should also remove that section as well:
https://github.com/Wikia/app/blob/dev/maintenance/language/messages.inc#L481-L498

**Comment by RafalWilinski** [comment]
I'll test that.

**Comment by RafalWilinski** [comment]
`$wgMessageStructure['passwordreset']` array is not used anywhere so I think it's safe to remove it.

**Pull request merged**
