### PR TITLE
XW 3401 | Install DS with support for hover on dropdowns

### PR DESCRIPTION
**Pull request by hakubo**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/9bb4a1d3d2f2d2d5ee30022bc9ce3d72f98fa188/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/9bb4a1d3d2f2d2d5ee30022bc9ce3d72f98fa188/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/ab8aac51573965b01d06fd9c4f98a9b114862d66/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/ab8aac51573965b01d06fd9c4f98a9b114862d66/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationNotifications.js#L52](https://github.com/Wikia/app/blob/90b578194254b642acfedddb00a3af4e28c46093/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationNotifications.js#L52): Remove the unused function parameter "ev". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
1. ![MAJOR][MAJOR] [DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10](https://github.com/Wikia/app/blob/90b578194254b642acfedddb00a3af4e28c46093/extensions/wikia/DesignSystem/scripts/DesignSystemGlobalNavigationOnSiteNotifications.view.js#L10): Function has 8 parameters which is greater than 4 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=javascript%3AExcessiveParameterList)

[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by rybmat** [comment]
will be done together with https://wikia-inc.atlassian.net/browse/XW-3296

**Pull request closed without merging**
