### PR TITLE
CON-2257 media galleries float fix

### PR DESCRIPTION
**Pull request by macbre**
Pinging @lizlux (code ownership)

### CODE REVIEW

**Comment by wladekb** [comment]
@lizlux @macbre @RafLeszczynski ping

**Comment by lizlux** [comment]
I've updated this PR so @macbre, @michalroszka, @RafLeszczynski please CR.

**Comment by macbre** [comment]
LGTM

**Comment by lizlux** [comment]
Closing this in favor of https://github.com/Wikia/app/pull/6291

**Pull request closed without merging**
