### PR TITLE
ensure all ForumBoard are showed even if they are not have sort order in wikia props

### PR DESCRIPTION
**Pull request by sqreek**
https://wikia-inc.atlassian.net/browse/SUS-388

@Wikia/sustaining-engineering-team

### CODE REVIEW

**Comment by pawelchcki** [comment]
Looks good
But how do we know it wont melt down the DB ?

**Comment by sqreek** [comment]
```
SELECT /* Forum::getBoardList 91.102.115.105 - 9d7552d7-6ac7-4a31-be9f-8a47fc7580d7 */  page.*  FROM `page`  WHERE page.page_namespace = '2000'  ORDER BY page_title
```

**Comment by pawelchcki** [comment]
If I understand this correctly - before you had to fetch page id by separate query for each entry?  And now its prepopulated ? so you only fetch page.ids only once ?

**Comment by pawelchcki** [comment]
Ok we discussed differences with previous PR offline. 
So now it LGTM

**Comment by ghost** [comment]
Was it about the `JOIN`?

**Comment by pawelchcki** [comment]
https://github.com/Wikia/app/pull/10122/commits/799f85890f30d936b775abbf69bcea4df38ae4bd#diff-246b95c08953161176632a5dbc3a5fffL44

**Comment by sqreek** [comment]
Long story short:
previously I modified getTitlesForNamespace and removed join there.
That cause all wall got Cartesian result.

here I only load all boards for special:Forum, and add missing order for those that dont contains order in page_wikia_props.

**Pull request merged**
