### PR TITLE
SUS-214: fallback to $wgFavicon instead of Community Central if no favicon exists on the wiki

### PR DESCRIPTION
**Pull request by mszabo-wikia**
Ticket & QA notes: https://wikia-inc.atlassian.net/browse/SUS-214

@mixth-sense

### CODE REVIEW

**Comment by sqreek** [comment]
:+1:

**Comment by ghost** [comment]
Something is wrong here:

```
> var_dump( wfReplaceImageServer( $wgResourceBasePath . $wgFavicon ) );
wfReplaceImageServer: requested url http://slot1.images.wikia.nocookie.net/__cb1470739629/commonhttp://images.wikia.com/central/images/6/64/Favicon.ico
string(122) "http://slot1.images.wikia.nocookie.net/__cb1470739629/commonhttp://img3.wikia.nocookie.net/central/images/6/64/Favicon.ico"
```

Executed with `SERVER_ID=177` on `cron-s1` - something environment-specific?

**Comment by mszabo-wikia** [comment]
@mixth-sense removed `wfReplaceImageServer` call, it wasn't needed and was causing this error

**Comment by ghost** [comment]
I don't think the problem is with `wfReplaceImageServer()`. It is that `$wgFavicon` already contains the full URL and does not have to be concatenated with `$wgResourceBasePath`.

**Comment by ghost** [comment]
LGTM :+1:

**Pull request merged**
