### PR TITLE
Remove Unused Extensions

### PR DESCRIPTION
**Pull request by ghost**
## [GO HERE](https://github.com/Wikia/app/pull/6598)

This initiative has been moved to ["Million Lines for Władek" challenge](https://github.com/Wikia/app/pull/6598) :-)
### Old text:

Github seems lying about the number of lines. It is 120k+ lines removed in this changeset. :-)

```
$ git diff --shortstat dev..dev-remove-unused-extensions 
571 files changed, 122273 deletions(-)
```

Today's lucky retirees are (in order of disappearance):
- `AutoProxyBlock` — http://www.mediawiki.org/wiki/Extension:AutoProxyBlock
- `Babel` — http://www.mediawiki.org/wiki/Extension:Babel
- `RdfRedland` — this is really, _really_, **really** old stuff
- `Narayam` — http://www.mediawiki.org/wiki/Extension:Narayam
- `WikimediaMaintenance` — http://www.mediawiki.org/wiki/Extension:WikimediaMaintenance
- `SignupAPI` — http://www.mediawiki.org/wiki/Extension:SignupAPI
- `ImportUsers` — http://www.mediawiki.org/wiki/Extension:ImportUsers
- `DeleteBatch` and `SpecialDeleteBatch` — http://www.mediawiki.org/wiki/Extension:DeleteBatch (plus Wikia's hackaround)
- `uniwiki` — http://www.mediawiki.org/wiki/Category:Uniwiki
- `WikiSync` — http://www.mediawiki.org/wiki/Extension:WikiSync
- `SoundManager2Button` — http://www.mediawiki.org/wiki/Extension:SoundManager2Button
- `Memorize` — http://www.mediawiki.org/wiki/Extension:Memorize
- `Woopra` — http://www.mediawiki.org/wiki/Extension:Woopra
- `MirrorTools` — http://www.mediawiki.org/wiki/Extension:MirrorTools
- `NetworkAuth` — http://www.mediawiki.org/wiki/Extension:NetworkAuth
- `WikiTextLoggedInOut` — http://www.mediawiki.org/wiki/Extension:WikiTextLoggedInOut
- `MakeDBError` — http://www.mediawiki.org/wiki/Extension:MakeDBError
- `WikiBhasha` — http://www.mediawiki.org/wiki/Extension:WikiBhasha

### CODE REVIEW

**Comment by wladekb** [comment]
R.I.P.

**Comment by wladekb** [comment]
I really like removing RdfRedland containing a lot of files with the same names as core files in includes/... and I needed to be very cautious when using autocomplete of file names.

**Comment by michalroszka** [comment]
Less is mrrr... :-)

**Comment by hakubo** [comment]
LGTM

**Pull request closed without merging**
