### PR TITLE
SUS-2001 | adapt multilookup to new field

### PR DESCRIPTION
**Pull request by idradm**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 14 issues
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L112](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L112): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgRequest" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$sk". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$wiki_meta". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): This function has 8 parameters, which is greater than the 7 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgContLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L285](https://github.com/Wikia/app/blob/6b10c1d503d342511a80a351d129dc2d300945c2/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L285): Remove this unused "$page_user" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Review by ghost — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 14 issues
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L112](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L112): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgRequest" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$sk". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$wiki_meta". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): This function has 8 parameters, which is greater than the 7 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgContLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L285](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L285): Remove this unused "$page_user" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 97 issues
* ![CRITICAL][CRITICAL] 1 critical
* ![MAJOR][MAJOR] 60 major
* ![MINOR][MINOR] 18 minor
* ![INFO][INFO] 18 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![CRITICAL][CRITICAL] [SpecialNewWikis_body.php#L273](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialNewWikis/SpecialNewWikis_body.php#L273): Only the first line of this 3-line block will be executed in a loop. The rest will execute only once. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS2681)
1. ![MAJOR][MAJOR] [SetupWikiCities.php#L12](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/CreateNewWiki/tasks/SetupWikiCities.php#L12): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1142)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L112](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L112): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgRequest" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$sk". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$wiki_meta". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): This function has 8 parameters, which is greater than the 7 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/00fec5cf184810e282e535a972efb35a1e88e8bb/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgContLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)

[CRITICAL]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-critical.png 'Severity: CRITICAL'
[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'
[MINOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 14 issues
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L112](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L112): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgRequest" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$sk". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$wiki_meta". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): This function has 8 parameters, which is greater than the 7 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgContLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L285](https://github.com/Wikia/app/blob/312f2bab68901a027c62ee5976176fb3b98f9bf6/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L285): Remove this unused "$page_user" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 14 issues
* ![MAJOR][MAJOR] 10 major
* ![INFO][INFO] 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L112](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L112): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgRequest" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L151](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L151): Remove this unused "$wgLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$sk". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): Remove the unused function parameter "$wiki_meta". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1172)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L226](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L226): This function has 8 parameters, which is greater than the 7 authorized. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS107)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgContLang" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L227](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L227): Remove this unused "$wgOut" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [SpecialMultipleLookup_helper.php#L285](https://github.com/Wikia/app/blob/39ecf1ccf3264d615264cb8ff94a8515061d7f31/extensions/wikia/SpecialMultipleLookup/SpecialMultipleLookup_helper.php#L285): Remove this unused "$page_user" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)

[INFO]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-info.png 'Severity: INFO'
[MAJOR]: https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-major.png 'Severity: MAJOR'

**Review by ghost — APPROVED** [review]

**Review by ghost — APPROVED** [review]

**Pull request merged**
