### PR TITLE
Grant "smw-patternedit" right Wikia Staff members

### PR DESCRIPTION
**Pull request by macbre**
https://wikia-inc.atlassian.net/browse/SUS-1297

See https://github.com/Wikia/config/pull/2009

@TK-999

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 21 issues
* MAJOR 4 major
* MINOR 14 minor
* INFO 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [PermissionsConfigurationImpl.php#L438](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L438): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L440](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L440): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L442](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L442): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L444](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L444): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MINOR [PermissionsConfigurationImpl.php#L26](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L26): Define a constant instead of duplicating this literal "content-reviewer" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L28](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L28): Define a constant instead of duplicating this literal "helper" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L31](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L31): Define a constant instead of duplicating this literal "restricted-login-exempt" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L33](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L33): Define a constant instead of duplicating this literal "staff" 8 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L34](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L34): Define a constant instead of duplicating this literal "translator" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L36](https://github.com/Wikia/app/blob/5f3c9f11a885c38db459b8630218ba6d8bad15a3/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L36): Define a constant instead of duplicating this literal "vanguard" 5 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Review by mszabo-wikia — APPROVED** [review]
LGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 21 issues
* MAJOR 4 major
* MINOR 14 minor
* INFO 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [PermissionsConfigurationImpl.php#L438](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L438): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L440](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L440): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L442](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L442): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L444](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L444): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MINOR [PermissionsConfigurationImpl.php#L26](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L26): Define a constant instead of duplicating this literal "content-reviewer" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L28](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L28): Define a constant instead of duplicating this literal "helper" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L31](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L31): Define a constant instead of duplicating this literal "restricted-login-exempt" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L33](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L33): Define a constant instead of duplicating this literal "staff" 8 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L34](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L34): Define a constant instead of duplicating this literal "translator" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L36](https://github.com/Wikia/app/blob/eead2eb6ba683c1efd859a46dd36879e1eccef6f/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L36): Define a constant instead of duplicating this literal "vanguard" 5 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 21 issues
* MAJOR 4 major
* MINOR 14 minor
* INFO 3 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [PermissionsConfigurationImpl.php#L438](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L438): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L440](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L440): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L442](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L442): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MAJOR [PermissionsConfigurationImpl.php#L444](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L444): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. MINOR [PermissionsConfigurationImpl.php#L26](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L26): Define a constant instead of duplicating this literal "content-reviewer" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L28](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L28): Define a constant instead of duplicating this literal "helper" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L31](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L31): Define a constant instead of duplicating this literal "restricted-login-exempt" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L33](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L33): Define a constant instead of duplicating this literal "staff" 8 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L34](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L34): Define a constant instead of duplicating this literal "translator" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [PermissionsConfigurationImpl.php#L36](https://github.com/Wikia/app/blob/8ab0e6ab36bb0dcff2b6518a8dd5631931a7dbc8/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L36): Define a constant instead of duplicating this literal "vanguard" 5 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Pull request merged**
