### PR TITLE
CE-3627: Force user registration rather than singing in modal

### PR DESCRIPTION
**Pull request by lukaszkonieczny**
Force user registration rather than singing in modal

ping @kvas-damian @rafalkalinski @bkoval @Wikia/spitfires

### CODE REVIEW

**Comment by kvas-damian** [comment]
LGTM

**Comment by lukaszkonieczny** [comment]
Let's complete it ! ;)
ping @kvas-damian @bkoval @rafalkalinski @Wikia/west-wing

**Comment by dianafa** [comment]
LGTM

**Comment by idradm** [comment]
LGTM as long as we want to change default behaviour to register for all this features

**Comment by rafalkalinski** [comment]
LGTM

**Pull request merged**
