### PR TITLE
XW-700 | Remove old endpoints in CuratedContentController and CuratedContentValidatorController

### PR DESCRIPTION
**Pull request by vforge**
https://wikia-inc.atlassian.net/browse/XW-700

/cc @bognix

### CODE REVIEW

**Comment by bognix** [comment]
you still need to remove some stuff in Mercury AFAIK

**Comment by vforge** [comment]
Yup, it's not done :)

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by vforge** [comment]
@bognix No need to do that - we did it before.

**Pull request merged**
