### PR TITLE
XW-2316 | Translate example value for Infobox Migration tool

### PR DESCRIPTION
**Pull request by kvas-damian**
https://wikia-inc.atlassian.net/browse/XW-2316

Ping @Wikia/x-wing

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [TemplateConverter.class.php#L57](https://github.com/Wikia/app/blob/535aeb797f6da59d4cbd67d51213f652c3e1a39d/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L57): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L84](https://github.com/Wikia/app/blob/535aeb797f6da59d4cbd67d51213f652c3e1a39d/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L84): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L96](https://github.com/Wikia/app/blob/535aeb797f6da59d4cbd67d51213f652c3e1a39d/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L96): Define a constant instead of duplicating this literal "default" 5 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L119](https://github.com/Wikia/app/blob/535aeb797f6da59d4cbd67d51213f652c3e1a39d/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L119): Define a constant instead of duplicating this literal "label" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L129](https://github.com/Wikia/app/blob/535aeb797f6da59d4cbd67d51213f652c3e1a39d/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L129): Immediately return this expression instead of assigning it to the temporary variable "$data". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L151](https://github.com/Wikia/app/blob/535aeb797f6da59d4cbd67d51213f652c3e1a39d/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L151): Immediately return this expression instead of assigning it to the temporary variable "$return". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. INFO [TemplateConverter.class.php#L8](https://github.com/Wikia/app/blob/535aeb797f6da59d4cbd67d51213f652c3e1a39d/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L8): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [TemplateConverter.class.php#L57](https://github.com/Wikia/app/blob/0f05dc29c2b9fc3031acc76274568ce4b49b6612/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L57): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L84](https://github.com/Wikia/app/blob/0f05dc29c2b9fc3031acc76274568ce4b49b6612/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L84): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L96](https://github.com/Wikia/app/blob/0f05dc29c2b9fc3031acc76274568ce4b49b6612/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L96): Define a constant instead of duplicating this literal "default" 5 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L119](https://github.com/Wikia/app/blob/0f05dc29c2b9fc3031acc76274568ce4b49b6612/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L119): Define a constant instead of duplicating this literal "label" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L129](https://github.com/Wikia/app/blob/0f05dc29c2b9fc3031acc76274568ce4b49b6612/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L129): Immediately return this expression instead of assigning it to the temporary variable "$data". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L151](https://github.com/Wikia/app/blob/0f05dc29c2b9fc3031acc76274568ce4b49b6612/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L151): Immediately return this expression instead of assigning it to the temporary variable "$return". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. INFO [TemplateConverter.class.php#L8](https://github.com/Wikia/app/blob/0f05dc29c2b9fc3031acc76274568ce4b49b6612/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L8): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [TemplateConverter.class.php#L57](https://github.com/Wikia/app/blob/6d74d94576491dfd16dc6552799d4c4332b5883a/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L57): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L84](https://github.com/Wikia/app/blob/6d74d94576491dfd16dc6552799d4c4332b5883a/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L84): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L96](https://github.com/Wikia/app/blob/6d74d94576491dfd16dc6552799d4c4332b5883a/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L96): Define a constant instead of duplicating this literal "default" 5 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L119](https://github.com/Wikia/app/blob/6d74d94576491dfd16dc6552799d4c4332b5883a/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L119): Define a constant instead of duplicating this literal "label" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L129](https://github.com/Wikia/app/blob/6d74d94576491dfd16dc6552799d4c4332b5883a/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L129): Immediately return this expression instead of assigning it to the temporary variable "$data". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L151](https://github.com/Wikia/app/blob/6d74d94576491dfd16dc6552799d4c4332b5883a/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L151): Immediately return this expression instead of assigning it to the temporary variable "$return". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. INFO [TemplateConverter.class.php#L8](https://github.com/Wikia/app/blob/6d74d94576491dfd16dc6552799d4c4332b5883a/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L8): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Review by weronika — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [TemplateConverter.class.php#L57](https://github.com/Wikia/app/blob/bdbf4c112972dd96b2660f5d99a242a7510b5460/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L57): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L84](https://github.com/Wikia/app/blob/bdbf4c112972dd96b2660f5d99a242a7510b5460/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L84): Immediately return this expression instead of assigning it to the temporary variable "$draft". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L96](https://github.com/Wikia/app/blob/bdbf4c112972dd96b2660f5d99a242a7510b5460/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L96): Define a constant instead of duplicating this literal "default" 5 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L119](https://github.com/Wikia/app/blob/bdbf4c112972dd96b2660f5d99a242a7510b5460/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L119): Define a constant instead of duplicating this literal "label" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [TemplateConverter.class.php#L129](https://github.com/Wikia/app/blob/bdbf4c112972dd96b2660f5d99a242a7510b5460/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L129): Immediately return this expression instead of assigning it to the temporary variable "$data". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [TemplateConverter.class.php#L151](https://github.com/Wikia/app/blob/bdbf4c112972dd96b2660f5d99a242a7510b5460/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L151): Immediately return this expression instead of assigning it to the temporary variable "$return". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. INFO [TemplateConverter.class.php#L8](https://github.com/Wikia/app/blob/bdbf4c112972dd96b2660f5d99a242a7510b5460/extensions/wikia/TemplateDraft/TemplateConverter.class.php#L8): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Review by Warkot — APPROVED** [review]

**Pull request merged**
