### PR TITLE
UC-195 | links to Terms of Use are now opened in new window by html

### PR DESCRIPTION
**Pull request by rafalkalinski**
https://wikia-inc.atlassian.net/browse/UC-195

### CODE REVIEW

**Comment by lizlux** [comment]
I checked out this code and tried it here http://lizlux.liz.wikia-dev.com/wiki/Special:UserSignup and the link at the bottom of the form didn't open in a new window, nor did the on inside the facebook signup/login modal. Am I doing something wrong?

Also, please add a description for this PR per the [pull request guidelines](https://github.com/Wikia/guidelines/blob/master/Process/PullRequests.md).

**Comment by kvas-damian** [comment]
I found pl and zh translation that're not updated: 
https://raw.githubusercontent.com/Wikia/app/uc-195/extensions/wikia/MessageOverrides/MessageOverrides.i18n.php

**Comment by kvas-damian** [comment]
@lizlux It work on my devbox, did you try rebuilding messages ```?rebuildmessages``` ?

**Comment by kvas-damian** [comment]
OK, the problem is that ```MessageOverrides.i18n.php``` is not used in our code base anymore.
Those translations lives only on messaging.wikia.com. I'll update them on production.

**Comment by lizlux** [comment]
Still doesn't work on my devbox, (tried rebuilding messages), but if you guys think it will work on production, then I suppose we can pass this to QA. It will have to work on the video dev box (or Qaga's devbox) for QA to be able to test it. Lemme know if you want me to look further into why this isn't working for me, or if you think you know what the problem is. Messaging environments and overrides can be tricky sometimes.

**Comment by lizlux** [comment]
Also, thanks for creating that ticket. Message Overrides has been a source of confusion for sure.

**Comment by lizlux** [comment]
Code LGTM (as long as it actually works ;))

**Comment by kvas-damian** [comment]
@lizlux This message was present on US devbox messaging wiki:
http://messaging.<hidden-devbox-domain>/wiki/MediaWiki:Prefs-help-terms?action=history

**Pull request merged**
