### PR TITLE
CONCF-612 | Scroll bar for windows with large modals is missing

### PR DESCRIPTION
**Pull request by vforge**
https://wikia-inc.atlassian.net/browse/CONCF-612
/cc @bognix @Warkot

### CODE REVIEW

**Comment by Warkot** [comment]
What about this comment `scrollbar blinking while preview`? Is it not blinking even after removing the fix?

**Comment by vforge** [comment]
@Warkot I haven't noticed that bug re-appearing.

**Comment by Warkot** [comment]
@vforge Cool, I hope QMs and our users won't deny your version. :smiley: LGTM then! :shipit:

**Comment by bognix** [comment]
LGTM

**Comment by rogatty** [comment]
LGTM

**Comment by bognix** [comment]
LGTM

**Pull request merged**
