### PR TITLE
SUS-323 / VOLDEV-16 | Category Exhibition does not let you expand subcategories

### PR DESCRIPTION
**Pull request by mszabo-wikia**
https://wikia-inc.atlassian.net/browse/VOLDEV-16 & https://wikia-inc.atlassian.net/browse/SUS-323
@Grunny @michalroszka

### CODE REVIEW

**Comment by wladekb** [comment]
@Grunny ping

**Comment by wladekb** [comment]
@Grunny @michalroszka ping

**Comment by TK-999** [comment]
@Grunny :smile:

**Comment by TK-999** [comment]
@Wikia/sustaining-team , @Grunny said this might be within your scope? :)

**Comment by Grunny** [comment]
Requested by TK to ping @Wikia/sustaining-team on this PR for review. :)

**Comment by TK-999** [comment]
@ttg

**Pull request closed without merging**
