### PR TITLE
Make Special:HealthCheck a bit lighter

### PR DESCRIPTION
**Pull request by macbre**
[PLATFORM-2131](https://wikia-inc.atlassian.net/browse/PLATFORM-2131)
- skip the internal POST request
- skip load checks
- leave the `host_disabled` check

@wladekb / @owend / @ljagiello

### CODE REVIEW

**Comment by wladekb** [comment]
I remember there was a reason for this POST check, let me find it out before merging...

**Comment by macbre** [comment]
`WebStart.php` has a check for read-only mode - it simply dies when MediaWiki is asked to handle POST request in read-only mode. However, we were not making POST request from HealthCheck when read-only was on.

**Comment by wladekb** [comment]
I couldn't find an exact reason for that so let's proceed with that.

**Comment by wladekb** [comment]
lgtm

**Comment by owend** [comment]
LGTM

**Pull request merged**
