### PR TITLE
CE-3120 Hide Navigation templates with block elements on mercury

### PR DESCRIPTION
**Pull request by adamkarminski**
/cc: @Wikia/community-engineering

### CODE REVIEW

**Comment by Grunny** [comment]
This should have unit tests added.

**Comment by adamkarminski** [comment]
@Grunny - It does now. :)

**Comment by Grunny** [comment]
LGTM in general. It's an edge case, but it's possible there may be unintentional false positives with the string matching method used. For example, we have a few parser tags that would match `<p` such as `<poem` (though that is kind of a block in itself). We may want to consider tightening it up a little with a regex.

**Comment by Grunny** [comment]
:+1:

**Comment by azarek** [comment]
Testing done! LGTM!

**Pull request merged**
