### PR TITLE
XW-396 | VOLDEV-145 - Implement article header changes and new rail module

### PR DESCRIPTION
**Pull request by Warkot**
:hand: :cop: :warning: **WIP — do not merge (yet)!**

Original PR: https://github.com/Wikia/app/pull/8301

XW ticket: https://wikia-inc.atlassian.net/browse/XW-396
Original VOLDEV ticket: https://wikia-inc.atlassian.net/browse/VOLDEV-145

### CODE REVIEW

**Comment by onei** [comment]
@Warkot I've fixed the merge conflicts with #8301. I don't know which is easier for you to test with, but if it happens again feel free to give me a nudge and I'll sort it out asap :)

**Comment by Warkot** [comment]
@onei Awesome! :+1: Thank you, I'll grab it then. :)

**Comment by Warkot** [comment]
@onei I've checked out the original branch after your merge (commit 81408cfbe4daba83f6645ed8c6d56fe1b1d8132c) on my devbox, but I'm afraid it doesn't work the same way as it didn't work before my hotfix (commit 954650e1307da25b8e0bc40b231f32a677a877f7). → `/usr/wikia/source/app/includes/wikia/nirvana/WikiaView.class.php:131 Template file not found: /usr/wikia/source/app/skins/oasis/modules/templates/ContributeController_index.php`, so it's not the problem with merge. :disappointed:

**Comment by onei** [comment]
The merge conflict fix was to allow it to be merged automatically rather than fix a bug, however that's not an error I've come across during testing. I'm limited to my vagrant devbox, but it looks like you're using a different setup judging by the path in the error which might possibly explain it? Having said that I'm running it on windows which has a habit of adding interesting quirks so I'm not too sure.

**Comment by onei** [comment]
@Warkot I think I've figured out the issue - Windows considers file names to be case insensitive which somehow spilled over to my devbox. I've renamed the template, so hopefully it should be working correctly now.

**Comment by Warkot** [comment]
@onei Your fixes helped to resolve the issue — I ported them here and reverted my hotfix. :+1: But now I'm trying to track the problem why the content of the page (i.e. of the `<div id="WikiaArticle" …>`) is not loading — do you think it may share the root of the cause with the previous one, the case (in)sensitivity?

**Comment by onei** [comment]
@Warkot That one I can reproduce, but it seems to be fixed by a null edit - have you tried that? It's a bug I've noticed intermittently while working on something else, but I haven't managed to nail down the cause of it unfortunately.

P.S. If it's easier, we could chat on [Slack](https://wikia.slack.com/team/cam)?

**Pull request closed without merging**
