### PR TITLE
SUS-958 | remove extensions/Oversight

### PR DESCRIPTION
**Pull request by macbre**
https://wikia-inc.atlassian.net/browse/SUS-958

We use `extensions/3rdparty/Oversight` and `extensions/wikia/OversightCompanion` instead:

```
CommonExtensions.php
735-if( !empty( $wgEnableHideRevisionExt ) ) {
736:	include( "$IP/extensions/3rdparty/Oversight/HideRevision.php" );
737-}
--
851-
852:if (!empty($wgEnableOversightCompanionExt)) {
853:	include( "$IP/extensions/wikia/OversightCompanion/OversightCompanion.php" );
854-}
```

`extensions/Oversight` is not referenced - let's remove it.

---

Since July 2012 <https://github.com/Wikia/app/blob/dev/extensions/Oversight/OBSOLETE> says:

> As of MediaWiki 1.16.0 this extension is obsolete due to core functionality for
revision deletion (oversight). As such, new installations of this extension are
redundant. This extension is not actively maintained, and is only really kept around
as it is still somewhat used on Wikimedia Wikis.
> 
> It will be deleted from subversion in the near future.

### CODE REVIEW

**Review by sqreek — APPROVED** [review]
👍 
also please check global messages for oversight messages, and is `oversight` permission is still in use

https://github.com/Wikia/app/blob/4c62b74a37ffb15b2a57a45214ba94ee261db56e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L119-L119

**Comment by macbre** [comment]
Good point! `oversight` user right is used by `extensions/Oversight/` only.

```
$ ack-grep --php isAllowed | grep oversight
extensions/Oversight/HideRevision.hooks.php:53:		if( $wgUser->isAllowed( 'oversight' ) ) {
```

**Comment by macbre** [comment]
```
1) Wikia\Service\User\Permissions\UserPermissionsIntegrationTest::testShouldReturnPermissionsNotDuplicated
Failed asserting that an array contains 'oversight'.

/var/lib/jenkins/workspace/unitTests_php_branches/app/lib/Wikia/tests/Service/User/UserPermissionsIntegrationTest.php:182
/var/lib/jenkins/workspace/unitTests_php_branches/app/tests/run-test.php:26
```

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L425](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L425): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L427](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L427): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L429](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L429): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L431](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L431): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L136](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L136): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L137](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L137): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L164](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L164): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L425](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L425): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L427](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L427): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L429](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L429): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L431](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L431): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L136](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L136): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L137](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L137): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L164](https://github.com/Wikia/app/blob/f8fceb2eb4c641771fda47ebb763f4ebeb55f67d/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L164): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Pull request merged**
