### PR TITLE
Pick only page level targeting if possible (#17671)

### PR DESCRIPTION
**Pull request by vforge**
@Wikia/cake

### CODE REVIEW

**Comment by mklucsarits** [comment]
Why not just cherry-pick the previous merge commit? You don't need 2 PRs for hotfixing, unless that's some kind of policy for the repo.

**Comment by vforge** [comment]
It is cherry picking the merge. We need two PRs - one for MW and one for mw :)

**Comment by mklucsarits** [comment]
@vforge But there's already an app PR? https://github.com/Wikia/app/pull/17671

**Review by mklucsarits — APPROVED** [review]
This is fine, I just don't understand the purpose of two PRs, unless you need PR tests to run against the release branch.

**Pull request merged**
