### PR TITLE
IRIS-3933 - stop including timestamp in new unsubscribe links

### PR DESCRIPTION
**Pull request by katanka**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 18 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 7 minor
* ![INFO][INFO] 2 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EmailController.class.php#L8](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L8): Class "EmailController" has 48 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [EmailController.class.php#L171](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L171): Remove this unused "$contentType" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L173](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L173): Remove this unused "$priority" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L174](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L174): Remove this unused "$attachments" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L175](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L175): Remove this unused "$sourceType" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L473](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L473): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [EmailController.class.php#L497](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L497): Remove this unused "$validate" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L631](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L631): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [EmailController.class.php#L643](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L643): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MINOR][MINOR] [EmailController.class.php#L229](https://github.com/Wikia/app/blob/12badd2caa52287f48bdd7235d8dab49b38a1ab4/extensions/wikia/Email/EmailController.class.php#L229): Immediately return this expression instead of assigning it to the temporary variable "$to". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by slayful** [comment]
It's very likely I'm missing something @katanka, but is this enough?

Shouldn't we also update the un-subscription handler? As it is I believe the handler will get a null in the timestamp and exit on https://github.com/Wikia/app/pull/13100/files#diff-7010dd78ecb29c674fa5ad415e41b12cL63 and https://github.com/Wikia/app/pull/13100/files#diff-2434fdecfa7936d38afc5f6d92428cc3R1267

It seems to me there are two components to that whole process:
1. generating a link with params for the e-mail and accepting those params in handler
1. generating a unsub token and comparing the one from e-mail with the one in handler

So the first one is necessary for the handler to generate a new token and compare it with the one from the e-mail. If we remove the timestamp from one side we'll break how tokens are compared. If we remove the timestamp from both, we'll break old links.

I'm thinking, for the purpose of this ticket, could we just remove this part:
```
		#validate timestamp isnt spoiled (you only have 7 days)
		$timeCutoff = strtotime("7 days ago");
		if( $timestamp <= $timeCutoff ) {
			$wgOut->addWikiMsg( 'unsubscribe-badtime' );
			// $wgOut->addHTML("timestamp={$timestamp}\n"); #DEVL (remove before release)
			// $wgOut->addHTML("timeCutoff={$timeCutoff}\n"); #DEVL (remove before release)
			return;
		}
```

The timestamp will still be passed and used for token comparison, but the link should no longer expire.

Side note I'm pretty sure we should move `verifyUserSecretKey` out of `Wikia.php` and prolly nearer `EmailController` since I think it's only used there.

**Comment by WikiaTech** [comment]
SonarQube analysis reported 157 issues
* ![MAJOR][MAJOR] 125 major
* ![MINOR][MINOR] 13 minor
* ![INFO][INFO] 19 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EmailController.class.php#L8](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L8): Class "EmailController" has 48 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [EmailController.class.php#L171](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L171): Remove this unused "$contentType" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L173](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L173): Remove this unused "$priority" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L174](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L174): Remove this unused "$attachments" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L175](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L175): Remove this unused "$sourceType" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L473](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L473): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [EmailController.class.php#L497](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L497): Remove this unused "$validate" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L631](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L631): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [EmailController.class.php#L643](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/Email/EmailController.class.php#L643): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Unsubscribe.body.php#L29](https://github.com/Wikia/app/blob/9b99fd8306aca732dd857c69e8b8d20544c16c56/extensions/wikia/SpecialUnsubscribe/Unsubscribe.body.php#L29): Replace this legacy wfMsg* function call with one of the new i18n functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by katanka** [comment]
Good catch, I missed that. I made some changes here, and moved `veriyUserSecretKey` in the other PR.

**Review by slayful — APPROVED** [review]
So regardless if we want to remove timestamp the first version could remove this check I right?
https://github.com/Wikia/app/pull/13131/files#diff-7010dd78ecb29c674fa5ad415e41b12cR71

I’d be worried that without timestamp the hashes might be a bit too simple, but besides that LGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 156 issues
* ![MAJOR][MAJOR] 124 major
* ![MINOR][MINOR] 13 minor
* ![INFO][INFO] 19 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [EmailController.class.php#L8](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L8): Class "EmailController" has 48 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [EmailController.class.php#L171](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L171): Remove this unused "$contentType" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L173](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L173): Remove this unused "$priority" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L174](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L174): Remove this unused "$attachments" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L175](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L175): Remove this unused "$sourceType" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L473](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L473): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [EmailController.class.php#L497](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L497): Remove this unused "$validate" local variable. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1481)
1. ![MAJOR][MAJOR] [EmailController.class.php#L631](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L631): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [EmailController.class.php#L643](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/Email/EmailController.class.php#L643): Refactor this code to rely on RequestContext instead of context-dependent globals. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3AContextualWgVariableUsage)
1. ![MAJOR][MAJOR] [Unsubscribe.body.php#L29](https://github.com/Wikia/app/blob/1d4e2b0ce0e5f0518ad41b4fc8ac368b706c7405/extensions/wikia/SpecialUnsubscribe/Unsubscribe.body.php#L29): Replace this legacy wfMsg* function call with one of the new i18n functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
