### PR TITLE
Update _insights-settings.scss

### PR DESCRIPTION
**Pull request by penguinstyles**
Adding a bit of padding between the Insights navigation and the inner container.

### CODE REVIEW

**Comment by penguinstyles** [comment]
@kamilkoterba

**Comment by kamilkoterba** [comment]
Hi, sorry for the delay. I'm glad you still have an eye on this.

Can you tell me what is the reason for increasing nav width?

and btw while looking into code I thought you might want to increase space between nav and content and I added that here:
https://github.com/Wikia/app/pull/7496

**Comment by penguinstyles** [comment]
Hi, sorry for the delay. Yes, I was trying to add more space between the nav and content areas. Thanks.

**Comment by kamilkoterba** [comment]
:thumbsup:

**Pull request closed without merging**
