### PR TITLE
CuratedContent: get rid of Special:CuratedContent

### PR DESCRIPTION
**Pull request by macbre**
https://wikia-inc.atlassian.net/browse/SUS-477

And as a follow-up of https://wikia-inc.atlassian.net/browse/SUS-475 get rid of `SpecialPromote` extension and `PromoteImageReview` (is disabled site-wide by https://github.com/Wikia/config/pull/1982)

@mixth-sense / @TK-999 / @sebastianmarzjan

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [CuratedContent.setup.php#L7](https://github.com/Wikia/app/blob/773fa828a2328224898579d510d18b9b56a1c4e9/extensions/wikia/CuratedContent/CuratedContent.setup.php#L7): Define a constant instead of duplicating this literal "CuratedContent" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [CuratedContent.setup.php#L7](https://github.com/Wikia/app/blob/774082dced88b76066760c59e3d03cb707915df9/extensions/wikia/CuratedContent/CuratedContent.setup.php#L7): Define a constant instead of duplicating this literal "CuratedContent" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [CuratedContent.setup.php#L7](https://github.com/Wikia/app/blob/657e5fa2ea9857e77fda13bc61c0f09f07ca8c94/extensions/wikia/CuratedContent/CuratedContent.setup.php#L7): Define a constant instead of duplicating this literal "CuratedContent" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [CuratedContent.setup.php#L7](https://github.com/Wikia/app/blob/657e5fa2ea9857e77fda13bc61c0f09f07ca8c94/extensions/wikia/CuratedContent/CuratedContent.setup.php#L7): Define a constant instead of duplicating this literal "CuratedContent" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [CuratedContent.setup.php#L7](https://github.com/Wikia/app/blob/657e5fa2ea9857e77fda13bc61c0f09f07ca8c94/extensions/wikia/CuratedContent/CuratedContent.setup.php#L7): Define a constant instead of duplicating this literal "CuratedContent" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [CuratedContent.setup.php#L7](https://github.com/Wikia/app/blob/24c693b3ce0e7b64349a73e53fa18356afd8b530/extensions/wikia/CuratedContent/CuratedContent.setup.php#L7): Define a constant instead of duplicating this literal "CuratedContent" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by ghost** [comment]
Tested and accepted. :medal_sports:

**Pull request merged**
