### PR TITLE
SOC-1326 | Updated mTouched on user when MW session starts based on access_token

### PR DESCRIPTION
**Pull request by kvas-damian**
https://wikia-inc.atlassian.net/browse/SOC-1326

`Etag` is calculated based on date of last touch on Article and User. It just gets max value from those two.
https://github.com/Wikia/app/blob/dev/includes/wikia/Wikia.php#L2171-L2177

User last touched date is updated on every login:
https://github.com/Wikia/app/blob/dev/extensions/wikia/UserLogin/UserLoginSpecialController.class.php#L463
https://github.com/Wikia/app/blob/dev/includes/User.php#L2132

Unfortunately this is not true when user logs in though Helios. It could happen that last touch date on article is newer than last touch date on a user, then we serve ETag using touch date from Article. Kaboom! Varnish serves 304, browser renders cached version of the page - which is anon page.

To fix that issue we bump `mTouched` when we initialize MW session using `access_token` cookie.

ping @rafalkalinski @bkoval @harnash @macbre @michalroszka and thanks for help ;)

### CODE REVIEW

**Comment by macbre** [comment]
:+1:

**Comment by harnash** [comment]
LGTM

**Comment by rafalkalinski** [comment]
LGTM

**Comment by bkoval** [comment]
LGTM :rabbit2:

**Comment by garthwebb** [comment]
LGTM

**Pull request merged**
