### PR TITLE
SER-543 Adds new user_id query param for LogEventsApiController

### PR DESCRIPTION
**Pull request by mvaddib**
###### Change Description:

user-registration service will now send additional user_id param to MW LogEventsApiController to  add log entry with specified user from query param.

### CODE REVIEW

**Comment by sqreek** [comment]
In PHP we are using tabs over spaces.
otherwise LGTM

**Comment by sqreek** [comment]
@africazulu test are failing, please update branch to master, and check it again.

**Comment by mvaddib** [comment]
@sqreek  Seems that tests are working after merging dev branch

**Comment by sqreek** [comment]
👍

**Pull request merged**
