### PR TITLE
VOLDEV-75 - Fix long words overflow the right rail WikiActivity module

### PR DESCRIPTION
**Pull request by onei**
@Grunny

### CODE REVIEW

**Comment by Grunny** [comment]
@hakubo I'm not sure who owns this area, maybe Content Team? Would you be able to find someone to have a look if so? :)

**Comment by mszabo-wikia** [comment]
Good to go after conflicts resolution

**Comment by onei** [comment]
@tk-999 is this still used somewhere? I was under the impression the update rail had rendered this obsolete. The issue is closed in Jira, but I'd forgotten to close this as well

**Comment by mszabo-wikia** [comment]
True :(

**Pull request closed without merging**
