### PR TITLE
Make autogenerated SCSS sprite files conform with guidelines

### PR DESCRIPTION
**Pull request by wladekb**
Updates to SpriteService class that make it generate SCSS files that conform with our SCSS guidelines.

Due to indentation fix in SpriteServices.scss you'll probably want to look at the changes by ignoring whitespace changes using this link:
https://github.com/Wikia/app/pull/6406/files?w=1

/cc @macbre @saipetch

### CODE REVIEW

**Comment by macbre** [comment]
```php
passthru('scss-lint -c ~/.scss-lint.yml ' . $scss);
```

How is this file generated / populated? Is it going to be available on all devboxes?

**Comment by wladekb** [comment]
I just took it from https://github.com/Wikia/guidelines/blob/master/SCSS/.scss-lint.yml
Apparently I could just not commit this temp script but thought it might be helpful for someone in the future. Should I remove it? What's your opinion?

**Comment by macbre** [comment]
Let's keep it, but document in `lintSprites.php` script where `.scss-lint.yml` can be found.

**Comment by wladekb** [comment]
Unit test failure is unrelated to changes.

**Pull request merged**
