### PR TITLE
SEO-489 No on-the-fly sitemaps for talk pages and other disallowed namespaces

### PR DESCRIPTION
**Pull request by gabrys**

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 25 issues
* MAJOR 13 major
* MINOR 8 minor
* INFO 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [SpecialSitemap_body.php#L129](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L129): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)
1. MAJOR [SpecialSitemap_body.php#L191](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L191): Remove this unused "$wgContentNamespaces" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
1. MAJOR [SpecialSitemap_body.php#L208](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L208): Remove this unused "$page" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
1. MAJOR [SpecialSitemap_body.php#L315](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L315): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L317](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L317): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L334](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L334): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L336](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L336): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L455](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L455): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L528](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/Sitemap/SpecialSitemap_body.php#L528): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemapXmlController.class.php#L78](https://github.com/Wikia/app/blob/9be6a35bc8c357311baa170a43a82cf79d879948/extensions/wikia/SitemapXml/SpecialSitemapXmlController.class.php#L78): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 21 issues
* MAJOR 9 major
* MINOR 8 minor
* INFO 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [SpecialSitemap_body.php#L129](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L129): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)
1. MAJOR [SpecialSitemap_body.php#L191](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L191): Remove this unused "$wgContentNamespaces" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
1. MAJOR [SpecialSitemap_body.php#L208](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L208): Remove this unused "$page" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
1. MAJOR [SpecialSitemap_body.php#L315](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L315): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L317](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L317): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L334](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L334): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L336](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L336): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L455](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L455): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MAJOR [SpecialSitemap_body.php#L528](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L528): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
1. MINOR [SpecialSitemap_body.php#L46](https://github.com/Wikia/app/blob/b092f8eca0fc91de0fd92b95d1f36c5eb0ca064a/extensions/wikia/Sitemap/SpecialSitemap_body.php#L46): Define a constant instead of duplicating this literal "Sitemap" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 21 issues
- MAJOR 9 major
- MINOR 8 minor
- INFO 4 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MAJOR [SpecialSitemap_body.php#L129](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L129): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)
2. MAJOR [SpecialSitemap_body.php#L193](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L193): Remove this unused "$wgContentNamespaces" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
3. MAJOR [SpecialSitemap_body.php#L210](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L210): Remove this unused "$page" local variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1481)
4. MAJOR [SpecialSitemap_body.php#L317](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L317): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
5. MAJOR [SpecialSitemap_body.php#L319](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L319): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
6. MAJOR [SpecialSitemap_body.php#L336](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L336): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
7. MAJOR [SpecialSitemap_body.php#L338](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L338): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
8. MAJOR [SpecialSitemap_body.php#L457](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L457): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
9. MAJOR [SpecialSitemap_body.php#L530](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L530): Use "static" keyword instead of "self". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS2037)
10. MINOR [SpecialSitemap_body.php#L46](https://github.com/Wikia/app/blob/38e72b28868d6f0ec7bf106a9eaf44d58ed53e0f/extensions/wikia/Sitemap/SpecialSitemap_body.php#L46): Define a constant instead of duplicating this literal "Sitemap" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

**Comment by saipetch** [comment]
LGTM

**Pull request merged**
