### PR TITLE
WW-20: Remove Contributions experiments

### PR DESCRIPTION
**Pull request by kerriamber**
See https://github.com/Wikia/config/pull/1884
@Wikia/west-wing

### CODE REVIEW

**Comment by sebastianmarzjan** [comment]
LGTM

**Comment by idradm** [comment]
What about `VisualEditorTourExperiment` removed in config pull request?

**Comment by sebastianmarzjan** [comment]
Good catch! I grepped the code and missed that :|

**Comment by idradm** [comment]
LGTM

**Comment by sebastianmarzjan** [comment]
LGTM

**Pull request closed without merging**
