### PR TITLE
SOC-1290 Pass a wiki theme color into wiki variables

### PR DESCRIPTION
**Pull request by mklucsarits**
Pass a wiki theme color to Mercury.

Related Mercury PR: https://github.com/Wikia/mercury/pull/1514
Related ticket: https://wikia-inc.atlassian.net/browse/SOC-1290

@bkoval @garthwebb

### CODE REVIEW

**Comment by bkoval** [comment]
LGTM :santa:

**Comment by rafalkalinski** [comment]
LGTM

**Comment by garthwebb** [comment]
LGTM

**Comment by kvas-damian** [comment]
This data is already availablein MercuryApi: fallout.wikia.com/wikia.php?controller=MercuryApi&method=getWikiVariables

**Pull request closed without merging**
