### PR TITLE
SUS-519 Remove Hero Module code

### PR DESCRIPTION
**Pull request by sebastianmarzjan**
Has to be merged with https://github.com/Wikia/config/pull/1768

### CODE REVIEW

**Comment by vforge** [comment]
LGTM, Don't merge!

**Comment by WikiaTech** [comment]
SonarQube analysis reported 11 issues
* MAJOR 4 major
* MINOR 7 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [WikiFeaturesHelper.class.php#L157](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L157): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [WikiFeaturesHelper.class.php#L171](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L171): Merge this if statement with the enclosing one. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1066)
1. MAJOR [WikiFeaturesHelper.class.php#L171](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L171): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L71](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L71): Define a constant instead of duplicating this literal "normal" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Replace this "if-then-else" statement by a single "return" statement. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1126)
1. MINOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/a12c32b3e0efb0dd49630b5d952970c9c32dce2b/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Remove the literal "true" boolean value. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1125)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 11 issues
* MAJOR 4 major
* MINOR 7 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [WikiFeaturesHelper.class.php#L157](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L157): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [WikiFeaturesHelper.class.php#L171](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L171): Merge this if statement with the enclosing one. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1066)
1. MAJOR [WikiFeaturesHelper.class.php#L171](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L171): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L71](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L71): Define a constant instead of duplicating this literal "normal" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Replace this "if-then-else" statement by a single "return" statement. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1126)
1. MINOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Remove the literal "true" boolean value. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1125)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 11 issues
* MAJOR 4 major
* MINOR 7 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [WikiFeaturesHelper.class.php#L157](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L157): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MAJOR [WikiFeaturesHelper.class.php#L171](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L171): Merge this if statement with the enclosing one. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1066)
1. MAJOR [WikiFeaturesHelper.class.php#L171](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L171): Add curly braces around the nested statement(s). [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS121)
1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L71](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L71): Define a constant instead of duplicating this literal "normal" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Replace this "if-then-else" statement by a single "return" statement. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1126)
1. MINOR [WikiFeaturesHelper.class.php#L155](https://github.com/Wikia/app/blob/5510860eed3ab333d898e6fa5dab685d0d8e4d28/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L155): Remove the literal "true" boolean value. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1125)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/954f607d3ce245b001125f3edb9684f554cdf5a0/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/954f607d3ce245b001125f3edb9684f554cdf5a0/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
1. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/954f607d3ce245b001125f3edb9684f554cdf5a0/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [WikiFeaturesHelper.class.php#L69](https://github.com/Wikia/app/blob/954f607d3ce245b001125f3edb9684f554cdf5a0/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L69): Define a constant instead of duplicating this literal "normal" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Comment by ArturKlajnerok** [comment]
Conflicts are resolved in : 954f607, it's ready to merge now 👍

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MINOR [FinishCreateWikiController.class.php#L35](https://github.com/Wikia/app/blob/0bc7512cf45315eb787ca573bc8b30f17aa04a1d/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L35): Define a constant instead of duplicating this literal "button" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
2. MINOR [FinishCreateWikiController.class.php#L155](https://github.com/Wikia/app/blob/0bc7512cf45315eb787ca573bc8b30f17aa04a1d/extensions/wikia/CreateNewWiki/FinishCreateWikiController.class.php#L155): Immediately return this expression instead of assigning it to the temporary variable "$newMainPageText". [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1488)
3. MINOR [WikiFeaturesHelper.class.php#L20](https://github.com/Wikia/app/blob/0bc7512cf45315eb787ca573bc8b30f17aa04a1d/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L20): Define a constant instead of duplicating this literal "title" 6 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
4. MINOR [WikiFeaturesHelper.class.php#L69](https://github.com/Wikia/app/blob/0bc7512cf45315eb787ca573bc8b30f17aa04a1d/extensions/wikia/WikiFeatures/WikiFeaturesHelper.class.php#L69): Define a constant instead of duplicating this literal "normal" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)

**Pull request merged**
