### PR TITLE
SUS-1080: URL in Special:Contact needs to be updated for rebrand

### PR DESCRIPTION
**Pull request by macbre**
https://wikia-inc.atlassian.net/browse/SUS-1080

The following i18n strings were renamed:

```
'specialcontact-seclink-using-wikia' => 'How do I use Fandom?',
'specialcontact-sectitle-using-wikia' => 'Using Fandom',
'specialcontact-intro-using-wikia' => 'Now that you are a part of the community...',
```

@Grunny / @TK-999

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [SecMap.php#L6](https://github.com/Wikia/app/blob/9f92f3d1fa3d1e1c9142e466c7be1985c7b8a314/extensions/wikia/SpecialContact2/SecMap.php#L6): Define a constant instead of duplicating this literal "headerMsg" 4 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [SecMap.php#L7](https://github.com/Wikia/app/blob/9f92f3d1fa3d1e1c9142e466c7be1985c7b8a314/extensions/wikia/SpecialContact2/SecMap.php#L7): Define a constant instead of duplicating this literal "links" 5 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

**Review by mszabo-wikia — APPROVED** [review]
LGTM

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MINOR [SecMap.php#L6](https://github.com/Wikia/app/blob/a7e565a5724ae69976d5dbedbe68f92f67d810a4/extensions/wikia/SpecialContact2/SecMap.php#L6): Define a constant instead of duplicating this literal "headerMsg" 4 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
1. MINOR [SecMap.php#L7](https://github.com/Wikia/app/blob/a7e565a5724ae69976d5dbedbe68f92f67d810a4/extensions/wikia/SpecialContact2/SecMap.php#L7): Define a constant instead of duplicating this literal "links" 5 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

**Review by Grunny — APPROVED** [review]
LGTM.

**Pull request merged**
