### PR TITLE
AsyncTaskList::queue - allow to pass $priority arg to set the queue that will process given task(s)

### PR DESCRIPTION
**Pull request by macbre**
https://wikia-inc.atlassian.net/browse/SUS-1250

This will allow us to make the following call (and force SMW tasks to be processed by the queue with a smaller concurrency):

```php
\Wikia\Tasks\Tasks\BaseTask::batch( $tasks, \Wikia\Tasks\Queues\SMWQueue::NAME );
```

Currently `mediawiki_smw` queue processes all tasks for wikis that have SemanticMediaWiki enabled.

## Examples:

> Please note the value of `spawn_task_queue` that will be logged to ELK

A typical MediaWiki task (will be processed by generic queue):

```php
$title = Title::newMainPage(); $title->touchLinks();
```

```json
{"appname":"mediawiki","@timestamp":"2016-11-07T11:52:16.168504+00:00","@message":"AsyncTaskList::queue mw-C7E99144-DAB7-4885-90FA-FE51663A9B0B","@fields":{"app_name":"mediawiki","app_version":"dev","datacenter":"poz","environment":"dev","wiki_dbname":"yugioh","wiki_id":"410","maintenance_file":"/usr/wikia/source/app/maintenance/eval.php","maintenance_class":"CommandLineInc","client_ip":"127.0.0.1","span_id":"af3d59b8-cff4-4b2f-a319-d31d8333b367","trace_id":"386f096c-a3d6-449f-9a53-0e741b555fff"},"@exception":{"class":"Exception","message":"","code":0,"file":"/usr/wikia/source/app/includes/wikia/tasks/AsyncTaskList.class.php:359","trace":["/usr/wikia/source/app/includes/wikia/tasks/AsyncTaskList.class.php:459","/usr/wikia/source/app/includes/wikia/tasks/Tasks/BaseTask.class.php:158","/usr/wikia/source/app/includes/Title.php:4489","/usr/wikia/source/app/maintenance/eval.php(88) : eval()'d code:1","/usr/wikia/source/app/maintenance/eval.php:88"]},"@context":{"spawn_task_id":"mw-C7E99144-DAB7-4885-90FA-FE51663A9B0B","spawn_task_type":"celery_workers.external.execute","spawn_task_work_id":"85011dcbc31e1aeb040736bf7fe19b0cce377f72","spawn_task_args":"[{\"wiki_id\":\"410\",\"call_order\":[[0,0]],\"task_list\":[{\"class\":\"Wikia\\\\Tasks\\\\Tasks\\\\HTMLCacheUpdateTask\",\"calls\":[[\"purge\",[[\"pagelinks\"]]]],\"context\":{\"titleParams\":{\"namespace\":0,\"dbKey\":\"Main_Page\"}}}],\"created_by\":{\"name\":\"127.0.0.1\",\"id\":0},\"created_at\":1478519536.1684,\"trace_env\":{\"WIKIA_TRACER_X_TRACE_ID\":\"386f096c-a3d6-449f-9a53-0e741b555fff\",\"WIKIA_TRACER_X_REQUEST_ID\":\"386f096c-a3d6-449f-9a53-0e741b555fff\",\"WIKIA_TRACER_X_PARENT_SPAN_ID\":\"af3d59b8-cff4-4b2f-a319-d31d8333b367\",\"WIKIA_TRACER_X_CLIENT_IP\":\"127.0.0.1\",\"WIKIA_TRACER_X_REQUEST_ORIGIN_HOST\":\"dev-macbre\",\"WIKIA_TRACER_X_WIKIA_INTERNAL_REQUEST\":\"mediawiki\"}}]","spawn_task_queue":"mediawiki_main"}}
```

SMW-specific task (will be processed by `mediawiki_smw` queue with a lower concurrency that should prevent database traffic spikes:

```php
$job = new SMW\MediaWiki\Jobs\RefreshJob( Title::newMainPage() ); $job->insert();
```

```json
{"appname":"mediawiki","@timestamp":"2016-11-07T11:53:12.318769+00:00","@message":"AsyncTaskList::queue mw-F441F705-DD3B-4819-B00E-678182E74425","@fields":{"app_name":"mediawiki","app_version":"dev","datacenter":"poz","environment":"dev","wiki_dbname":"yugioh","wiki_id":"410","maintenance_file":"/usr/wikia/source/app/maintenance/eval.php","maintenance_class":"CommandLineInc","client_ip":"127.0.0.1","span_id":"af3d59b8-cff4-4b2f-a319-d31d8333b367","trace_id":"386f096c-a3d6-449f-9a53-0e741b555fff"},"@exception":{"class":"Exception","message":"","code":0,"file":"/usr/wikia/source/app/includes/wikia/tasks/AsyncTaskList.class.php:359","trace":["/usr/wikia/source/app/includes/wikia/tasks/AsyncTaskList.class.php:459","/usr/wikia/source/app/includes/wikia/tasks/Tasks/BaseTask.class.php:417","/usr/wikia/source/app/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobBase.php:149","/usr/wikia/source/app/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobBase.php:167","/usr/wikia/source/app/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/RefreshJob.php:73","/usr/wikia/source/app/maintenance/eval.php(88) : eval()'d code:1","/usr/wikia/source/app/maintenance/eval.php:88"]},"@context":{"spawn_task_id":"mw-F441F705-DD3B-4819-B00E-678182E74425","spawn_task_type":"celery_workers.external.execute","spawn_task_work_id":"85011dcbc31e1aeb040736bf7fe19b0cce377f72","spawn_task_args":"[{\"wiki_id\":\"410\",\"call_order\":[[0,0]],\"task_list\":[{\"class\":\"Wikia\\\\Tasks\\\\Tasks\\\\JobWrapperTask\",\"calls\":[[\"wrap\",[\"SMW\\\\RefreshJob\"]]],\"context\":{\"titleParams\":{\"namespace\":0,\"dbKey\":\"Main_Page\"},\"params\":{\"spos\":1,\"prog\":0,\"rc\":1}}}],\"created_by\":{\"name\":\"127.0.0.1\",\"id\":0},\"created_at\":1478519592.3187,\"trace_env\":{\"WIKIA_TRACER_X_TRACE_ID\":\"386f096c-a3d6-449f-9a53-0e741b555fff\",\"WIKIA_TRACER_X_REQUEST_ID\":\"386f096c-a3d6-449f-9a53-0e741b555fff\",\"WIKIA_TRACER_X_PARENT_SPAN_ID\":\"af3d59b8-cff4-4b2f-a319-d31d8333b367\",\"WIKIA_TRACER_X_CLIENT_IP\":\"127.0.0.1\",\"WIKIA_TRACER_X_REQUEST_ORIGIN_HOST\":\"dev-macbre\",\"WIKIA_TRACER_X_WIKIA_INTERNAL_REQUEST\":\"mediawiki\"}}]","spawn_task_queue":"mediawiki_smw"}}
```

I'll port 3e58a43 to [our SMW fork](https://github.com/Wikia/SemanticMediaWiki) and use composer to update our app code.

@mixth-sense / @TK-999 / @sqreek

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BaseTask.class.php#L16](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L16): Class "BaseTask" has 23 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [BaseTask.class.php#L60](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L60): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS112)
1. MINOR [AsyncTaskList.class.php#L349](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/AsyncTaskList.class.php#L349): Define a constant instead of duplicating this literal "exception" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [BaseTask.class.php#L58](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L58): Define a constant instead of duplicating this literal "dbKey" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. INFO [AsyncTaskList.class.php#L260](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/AsyncTaskList.class.php#L260): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BaseTask.class.php#L16](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L16): Class "BaseTask" has 23 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [BaseTask.class.php#L60](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L60): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS112)
1. MINOR [AsyncTaskList.class.php#L349](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/AsyncTaskList.class.php#L349): Define a constant instead of duplicating this literal "exception" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [BaseTask.class.php#L58](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L58): Define a constant instead of duplicating this literal "dbKey" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. INFO [AsyncTaskList.class.php#L260](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/AsyncTaskList.class.php#L260): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BaseTask.class.php#L16](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L16): Class "BaseTask" has 23 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [BaseTask.class.php#L60](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L60): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS112)
1. MINOR [AsyncTaskList.class.php#L349](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/AsyncTaskList.class.php#L349): Define a constant instead of duplicating this literal "exception" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [BaseTask.class.php#L58](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/Tasks/BaseTask.class.php#L58): Define a constant instead of duplicating this literal "dbKey" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. INFO [AsyncTaskList.class.php#L260](https://github.com/Wikia/app/blob/0d91fc897c8fd4cbab8eca9a1ef7a7da5bca4f9e/includes/wikia/tasks/AsyncTaskList.class.php#L260): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 5 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BaseTask.class.php#L16](https://github.com/Wikia/app/blob/dba1b15beee3983062cbee3ec475f5799dbb5555/includes/wikia/tasks/Tasks/BaseTask.class.php#L16): Class "BaseTask" has 23 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [BaseTask.class.php#L60](https://github.com/Wikia/app/blob/dba1b15beee3983062cbee3ec475f5799dbb5555/includes/wikia/tasks/Tasks/BaseTask.class.php#L60): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS112)
1. MINOR [AsyncTaskList.class.php#L349](https://github.com/Wikia/app/blob/dba1b15beee3983062cbee3ec475f5799dbb5555/includes/wikia/tasks/AsyncTaskList.class.php#L349): Define a constant instead of duplicating this literal "exception" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [BaseTask.class.php#L58](https://github.com/Wikia/app/blob/dba1b15beee3983062cbee3ec475f5799dbb5555/includes/wikia/tasks/Tasks/BaseTask.class.php#L58): Define a constant instead of duplicating this literal "dbKey" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. INFO [AsyncTaskList.class.php#L260](https://github.com/Wikia/app/blob/dba1b15beee3983062cbee3ec475f5799dbb5555/includes/wikia/tasks/AsyncTaskList.class.php#L260): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Review by ghost — APPROVED** [review]

**Comment by WikiaTech** [comment]
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BaseTask.class.php#L16](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/Tasks/BaseTask.class.php#L16): Class "BaseTask" has 23 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [BaseTask.class.php#L60](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/Tasks/BaseTask.class.php#L60): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS112)
1. MINOR [JobBase.php#L126](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobBase.php#L126): Remove the literal "false" boolean value. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1125)
1. MINOR [AsyncTaskList.class.php#L349](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/AsyncTaskList.class.php#L349): Define a constant instead of duplicating this literal "exception" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [BaseTask.class.php#L58](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/Tasks/BaseTask.class.php#L58): Define a constant instead of duplicating this literal "dbKey" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. INFO [AsyncTaskList.class.php#L260](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/AsyncTaskList.class.php#L260): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [BaseTask.class.php#L16](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/Tasks/BaseTask.class.php#L16): Class "BaseTask" has 23 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. MAJOR [BaseTask.class.php#L60](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/Tasks/BaseTask.class.php#L60): Define and throw a dedicated exception instead of using a generic one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS112)
1. MINOR [JobBase.php#L126](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/extensions/SemanticMediaWiki/src/MediaWiki/Jobs/JobBase.php#L126): Remove the literal "false" boolean value. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1125)
1. MINOR [AsyncTaskList.class.php#L349](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/AsyncTaskList.class.php#L349): Define a constant instead of duplicating this literal "exception" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. MINOR [BaseTask.class.php#L58](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/Tasks/BaseTask.class.php#L58): Define a constant instead of duplicating this literal "dbKey" 3 times. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1192)
1. INFO [AsyncTaskList.class.php#L260](https://github.com/Wikia/app/blob/3e58a436dc3f5b6e0f0d87d09634743987d50cdf/includes/wikia/tasks/AsyncTaskList.class.php#L260): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

**Comment by macbre** [comment]
Backported to preview branch in 8dd2b28 and to production in #11803

**Pull request merged**
