### PR TITLE
UC-77 Show an email entry box when FB does not supply it

### PR DESCRIPTION
**Pull request by garthwebb**
If the user unchecks the 'email' box when registering w/ our Facebook app, we won't get an email address for them from Facebook.  In that case we need to collect it from them before continuing.

https://wikia-inc.atlassian.net/browse/UC-77

### CODE REVIEW

**Comment by wladekb** [comment]
@garthwebb @lizlux @armonr ping

**Comment by armonr** [comment]
I think we can close this. @garthwebb ?

**Comment by garthwebb** [comment]
Not sure what happened with this PR.  The ticket was signed off on back in November so I'm guessing the proper code got out

**Comment by lizlux** [comment]
Yeah i merged this code with a different PR b/c there were going to be lot's of conflicts.

**Pull request closed without merging**
