### PR TITLE
SERVICES-1164 add prod tag to phalanx address

### PR DESCRIPTION
**Pull request by sqreek**
https://wikia-inc.atlassian.net/browse/SERVICES-1164

please merge this after email about [configuration change](https://github.com/Wikia/config/pull/1615)
ping @Wikia/services-team

### CODE REVIEW

**Comment by sqreek** [comment]
tests are not passing cause config change is not merged.

**Comment by ArturKlajnerok** [comment]
I don't think it's good idea to have this hardcoded in app, we should use the hostname & port from : `LocalSettings` see my comment on https://github.com/Wikia/config/pull/1615

**Comment by sqreek** [comment]
this code is for production. So default is always prod. Actually we don't need this change if we assume that every phalanx on production is production phalanx.

**Comment by harnash** [comment]
One more thing:

```
harnas@dev-harnas:~$ host phalanx.service.consul
phalanx.service.consul has address 10.14.30.159
phalanx.service.consul has address 10.14.30.175

harnas@dev-harnas:~$ host prod.phalanx.service.consul
Host prod.phalanx.service.consul not found: 3(NXDOMAIN)

harnas@dev-harnas:~$ host prod.phalanx.service.sjc.consul
prod.phalanx.service.sjc.consul has address 10.8.68.82
prod.phalanx.service.sjc.consul has address 10.8.62.73
prod.phalanx.service.sjc.consul has address 10.8.62.77
```

**Comment by harnash** [comment]
https://github.com/hashicorp/consul/issues/1721

**Comment by harnash** [comment]
So above comment is obviously wrong. It tries to find services with tag `prod` on my dev-box which is in `dev` data center.

**Comment by ArturKlajnerok** [comment]
So can we just remove `wgPhalanxServiceUrl` here as we will get the default from https://github.com/Wikia/config ? Sorry, for late response.

**Comment by sqreek** [comment]
ok , we can go to pure config setup.

**Pull request closed without merging**
