### PR TITLE
Upgrade MW version to latest

### PR DESCRIPTION
**Pull request by ludwikkazmierczak**
🏆:trollface:

### CODE REVIEW

**Review by macbre — CHANGES_REQUESTED** [review]
Do we have a testing plan for this significant change?

**Comment by rail01** [comment]
Latest MW release is 1.32, not 1.31 🙃 #deprecatedInUpdateDay

**Comment by ludwikkazmierczak** [comment]
> Latest MW release is 1.32, not 1.31 🙃 #deprecatedInUpdateDay

Thanks, updated :)

**Comment by HM100** [comment]
In order to be latest, it **MUST** contain all the changes that the version has otherwise, MW1.19 is the best for that one despite those backportd

**Comment by bkoval** [comment]
❤️

**Comment by nikodamn** [comment]
believe

**Comment by rail01** [comment]
> 
> 
> > Latest MW release is 1.32, not 1.31 🙃 #deprecatedInUpdateDay
> 
> Thanks, updated :)

I have [screenshot](https://i.imgur.com/JMrh2eC.png) of that changes in action ;)

**Comment by wwarren** [comment]
🤣

**Pull request closed without merging**
