### PR TITLE
SOC-1177 | Escape Chat frontend messages

### PR DESCRIPTION
**Pull request by kvas-damian**
https://wikia-inc.atlassian.net/browse/SOC-1177

Added new method for `mw.message` - `rawParams`. This way we can pass params that should not be escaped when using `escaped` format.

ping @Grunny @garthwebb @rafalkalinski 
PS. It's easier to use https://github.com/Wikia/app/compare/dev...4bbc4a54259d0ace94332835e017e7a2b3b33b9d for reviewing changes

### CODE REVIEW

**Comment by rafalkalinski** [comment]
LGTM

**Comment by Grunny** [comment]
LGTM. :) Might be cool to contribute this back up to the latest MW core as well if it applies easily enough, since they could make use of it as well.

**Comment by kvas-damian** [comment]
Will try when it passes QA.

**Comment by garthwebb** [comment]
LGTM

**Pull request merged**
