### PR TITLE
Ce 1528 fix user edits updates

### PR DESCRIPTION
**Pull request by kamilkoterba**
https://wikia-inc.atlassian.net/browse/CE-1528
User edits updates data doesn't arrive to ExactTarget,
data consistency for ExactTaget extension is highly important at the moment due to upcoming big sendouts.

Review of previous version of SQL querries
https://github.com/Wikia/app/pull/5893

@Wikia/community-engineering

### CODE REVIEW

**Comment by kamilkoterba** [comment]
## QUERY to statsdb

```
SELECT user_id, wiki_id, sum( edits ) + sum( creates ) AS editcount
	 FROM rollup_wiki_user_events
	 WHERE time_id > '2015-03-23 11:50:13'
	 AND period_id = '1'
	 AND user_id <> '0' GROUP BY wiki_id, user_id"
```
time_id condition is always 24h back in time.

EXPLAIN

```
+----+-------------+-------------------------+-------+-----------------+---------+---------+------+--------+----------------------------------------------+
| id | select_type | table                   | type  | possible_keys   | key     | key_len | ref  | rows   | Extra                                        |
+----+-------------+-------------------------+-------+-----------------+---------+---------+------+--------+----------------------------------------------+
|  1 | SIMPLE      | rollup_wiki_user_events | range | PRIMARY,time_id | PRIMARY | 8       | NULL | 107474 | Using where; Using temporary; Using filesort |
+----+-------------+-------------------------+-------+-----------------+---------+---------+------+--------+----------------------------------------------+
```

Worst case scenario is all our users edited on all our wikis in last 24 hours

@SQLReview

**Comment by lgarczewski** [comment]
LGTM from code side.

**Comment by wladekb** [comment]
SQL seems legit

but I have another question: The split of the work is a bit confusing for me. Fetching the list of work to do is done in a maintenance script and processing is done via Job Queue tasks. What is the reason for that flow? Could both stages be done using the same execution mechanism?

**Comment by kamilkoterba** [comment]
All updates are implemented as tasks and I'm using this mechanism here. I could run task directly without queuing it but this way I'm loosing logs in Celery. So to be consistent with a way we run all updates this one is also queued in Job Queue. Also update tasks are not responsible for gathering data, hence it's separate.

**Comment by wladekb** [comment]
lgtm

**Pull request merged**
