### PR TITLE
PhalanxFallback: log when called

### PR DESCRIPTION
**Pull request by macbre**
- log when we enter a fallback mode - i.e. use the old Phalanx logic that queries database and run regular expressions on PHP side
- remove unused `extensions/wikia/Phalanx`

@Wikia/sustaining-team

### CODE REVIEW

**Comment by adamkarminski** [comment]
Francis approves

**Comment by macbre** [comment]
Roma locuta causa finita? ;)

**Comment by ghost** [comment]
Do Special:Phalanx and Special:PhalanxStats work properly? :-)

**Comment by macbre** [comment]
Well, [yes](http://stable.community.wikia.com/wiki/Special:Phalanx) :-)

**Pull request merged**
