### PR TITLE
Introduce WikiaDatabaseTest class for using in-memory SQLite DB

### PR DESCRIPTION
**Pull request by mszabo-wikia**
Allow developers to write integration test using in-memory database due to the shortcomings of the current test execution environment.

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 17 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AutoLoader.php#](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/AutoLoader.php#): File "AutoLoader.php" has 1007 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L13](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L13): Class "DatabaseSqlite" has 59 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L125): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L529](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L529): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L584](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L584): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L591](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L591): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L613](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L613): Replace this legacy wfMsg* function call with one of the new i18n functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L846](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L846): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L891](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L891): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MINOR][MINOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/9f38769e55c91fda054c40aeeccc5cb2eb57446d/includes/db/DatabaseSqlite.php#L125): 2 statements were found on this line. Reformat the code to have only one statement per line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Review by macbre — APPROVED** [review]
This looks great! And example test would be nice.

**Comment by WikiaTech** [comment]
SonarQube analysis reported 17 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AutoLoader.php#](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/AutoLoader.php#): File "AutoLoader.php" has 1007 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L13](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L13): Class "DatabaseSqlite" has 59 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L125): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L529](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L529): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L584](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L584): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L591](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L591): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L613](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L613): Replace this legacy wfMsg* function call with one of the new i18n functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L846](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L846): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L891](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L891): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MINOR][MINOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/7bbc6932bc96f96368ae539fbcebe2d497afb295/includes/db/DatabaseSqlite.php#L125): 2 statements were found on this line. Reformat the code to have only one statement per line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 17 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AutoLoader.php#](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/AutoLoader.php#): File "AutoLoader.php" has 1007 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L13](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L13): Class "DatabaseSqlite" has 59 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L125): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L529](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L529): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L584](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L584): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L591](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L591): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L613](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L613): Replace this legacy wfMsg* function call with one of the new i18n functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L846](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L846): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L891](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L891): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MINOR][MINOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/d4c7ff32a31df074c58634afe0a7caf455d028ed/includes/db/DatabaseSqlite.php#L125): 2 statements were found on this line. Reformat the code to have only one statement per line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 17 issues
* ![MAJOR][MAJOR] 9 major
* ![MINOR][MINOR] 3 minor
* ![INFO][INFO] 5 info

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [AutoLoader.php#](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/AutoLoader.php#): File "AutoLoader.php" has 1007 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS104)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L13](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L13): Class "DatabaseSqlite" has 59 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1448)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L125): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L529](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L529): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L584](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L584): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L591](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L591): Remove this commented out code. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS125)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L613](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L613): Replace this legacy wfMsg* function call with one of the new i18n functions. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=wikia-php-rules%3ALegacyWfMsgUsage)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L846](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L846): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MAJOR][MAJOR] [DatabaseSqlite.php#L891](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L891): Merge this if statement with the enclosing one. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS1066)
1. ![MINOR][MINOR] [DatabaseSqlite.php#L125](https://github.com/Wikia/app/blob/eabe067de7366ee2193aab8bb6c26afa16d9bb4a/includes/db/DatabaseSqlite.php#L125): 2 statements were found on this line. Reformat the code to have only one statement per line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS122)

[project-id]: wikia:app
[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'
[MINOR]: https://sonarsource.github.io/sonar-github/severity-minor.png 'Severity: MINOR'

**Pull request merged**
