### PR TITLE
SUS-183: Return null if getApiWrapper returns null

### PR DESCRIPTION
**Pull request by inez**
Method getApiWrapper internally tries to figure our video provider and video id - if it fails it means that provided URL is incorrect - so we should not attempt to "uplod" such a broken URL.

### CODE REVIEW

**Comment by owend** [comment]
Looks like ApiWrapperFactory::getApiWrapper can return false or null so probably better to make an empty() check here or refactor that function to consistently return null.

**Comment by inez** [comment]
@owend Good catch!

**Comment by inez** [comment]
Ready for CR again.

**Comment by owend** [comment]
LGTM

**Pull request merged**
