### PR TITLE
INT-269: Adding fake query parameter to ping page view to GA, so that we know …

### PR DESCRIPTION
**Pull request by mari-mcmurtrie**
…inter and intra searches separately.

### CODE REVIEW

**Comment by mari-mcmurtrie** [comment]
@perjg this is Oasis one for INT-269. It is pretty much the same idea. Use qIntra for intra search, qInter for inter search. Will you CR? Thanks!

**Comment by perjg** [comment]
LGTM

**Comment by perjg** [comment]
@mari-mcmurtrie You should probably check why there is a unit test failure.

**Comment by mari-mcmurtrie** [comment]
Thanks @perjg . The test failure was intermittent. I am pretty sure it was not related with my change.

**Pull request merged**
