### PR TITLE
JPN-564 Download latest crowdin translations

### PR DESCRIPTION
**Pull request by perjg**
@Wikia/spitfires @d34th4ck3r 

There was an error in one of the Japanese strings which is corrected with this translation update. It should go out with the beta release.

### CODE REVIEW

**Comment by d34th4ck3r** [comment]
In JIRA it says : 'upload latest translation files for Japanese' but the text that you added has no Japanese in it.

**Comment by perjg** [comment]
@d34th4ck3r Yes it does, see a bit further down in the diff and you will find this:
-   'communitypage-entry-button' => 'コミュニティ内ページ',
  -  'communitypage-entry-button' => 'コミュニティ・ページ',

The English strings are new strings that were pulled in together with this translation.

**Comment by kamilkoterba** [comment]
I don't see a point for adding EN translations for languages that are still waiting to be translated as we have default fallback in MW.
Also here's a waiting PR: https://github.com/Wikia/app/pull/10621 can we merge them? If not I prefer surgically pull the message we want for beta release.

**Comment by perjg** [comment]
The en translations came in when I did 'crowdin download' should I just
manually change the Japanese one instead?

On Tuesday, 7 June 2016, kamilkoterba notifications@github.com wrote:

> I don't see a point for adding EN translations for languages that are
> still waiting to be translated as we have default fallback in MW.
> Also here's a waiting PR: #10621 https://github.com/Wikia/app/pull/10621
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> https://github.com/Wikia/app/pull/10630#issuecomment-224221808, or mute
> the thread
> https://github.com/notifications/unsubscribe/AAnu_BU8UfshTDeYupgIsKqZnUjOE635ks5qJTPBgaJpZM4IveJ-
> .

## 

Sincerely,
 Per Johan Groland
 Akafugu Corporation

Blog: http://www.akafugu.jp/blog/
Twitter: akafuguJP
Facebook: http://www.facebook.com/akafugu

**Comment by d34th4ck3r** [comment]
I just added some additional translation.

**Comment by lukaszkonieczny** [comment]
LGTM

**Pull request merged**
