### PR TITLE
PLATFORM-1007: rename MostimagesInContent to MostLinkedFilesInContent

### PR DESCRIPTION
**Pull request by macbre**
Use a bit different approach than in #6909 - rename only the special page name and i18n messages. Do not touch class names and query pages.

@jcellary

### CODE REVIEW

**Comment by jcellary** [comment]
LGTM

**Comment by macbre** [comment]
I need to change the query in `ImageServingDriverMainNS.class.php` to match the new name of the special page.

**Comment by macbre** [comment]
`MostimagesInContent` will still be used "internally":

* when refreshing the data via `updateSpecialPages.php` script
* by ImageServing when querying `querycache` table

**Comment by wladekb** [comment]
lgtm

**Pull request merged**
