### PR TITLE
JPN-482 Add more unique selectors prefix for entrypoint selectors

### PR DESCRIPTION
**Pull request by kamilkoterba**
@Wikia/spitfires @perjg I think just entry-point prefix is too generic. What do you think?

### CODE REVIEW

**Comment by lukaszkonieczny** [comment]
My only concern is should we have two different prefixes

**Comment by kamilkoterba** [comment]
Full prefix is on parent and abbreviation is added to childs

**Comment by kamilkoterba** [comment]
Changed approach to have consistency around all selectors and went with full prefixes

**Comment by lukaszkonieczny** [comment]
LGTM

**Pull request merged**
