### PR TITLE
CONCF-808 | use one variable to specify large breakpoint

### PR DESCRIPTION
**Pull request by hakubo**
having two many math experssions in scss is tricky
as we might come up with the same output
but we can create differen abstractions that can brake when we want to
change something else

@WikiaSparrow

### CODE REVIEW

**Comment by vforge** [comment]
Strange... If it's really the same then LGTM

**Comment by hakubo** [comment]
it differs by 2 px - I don't think this was intended

**Comment by hakubo** [comment]
Currently it is: 1576 + 20 = 1596
it used to be:
1238 + 2 \* 179 = 1596
oh and before the temp fix it used to be:
1238 + 2 \* 170 = 1578

 let me say this:
...

**Comment by vforge** [comment]
If it differs - it would be nice to have confirmation / test from AdEng

ping @nandy-andy

**Comment by hakubo** [comment]
no it does not differ, my bad

**Comment by bognix** [comment]
LGTM

**Comment by hakubo** [comment]
@nandy-andy should we run tests for it? if yes, which ?

**Comment by nandy-andy** [comment]
@hakubo sure! :smile_cat: To test if the skin behaves correctly run our selenium tests! `TestSkinPresence` which is in `TestSkinPresence_GeoEdgeFree` group. Additionally you can run `TestRoadblock_GeoEdgeFree` which is in `TestRoadblock_GeoEdgeFree` group :japanese_ogre: Much appreciated! :+1:

**Comment by vforge** [comment]
LGTM

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
