### PR TITLE
Remove facebookAppId from MercuryApi

### PR DESCRIPTION
**Pull request by kvas-damian**
Please don't merge until https://github.com/Wikia/mercury/pull/1236 is merged.

### CODE REVIEW

**Comment by rogatty** [comment]
LGTM

**Comment by bkoval** [comment]
LGTM :hamburger: :hammer:

**Comment by hakubo** [comment]
LGTM,

**Comment by rogatty** [comment]
Remember to not release before mercury code that is dependant on this is no longer in the fastly cache.

**Comment by kvas-damian** [comment]
It's going to be released on Tuesday, mercury is going to be released tomorrow, so there is no problem.

**Pull request merged**
