### PR TITLE
ADEN-2078 Fix 71Media skyscraper

### PR DESCRIPTION
**Pull request by nandy-andy**
Changes below fix 71Media skyscraper in Oasis with new breakpoints.

### CODE REVIEW

**Comment by vforge** [comment]
LGTM

**Comment by nandy-andy** [comment]
@vforge I've changed it a little bit - rebased branch with the newest changes dony by @bognix and added more code which will replace the old code once breakpoints will be released everywhere :japanese_ogre: Feel free to CR again, guys :smile:

**Comment by gabrys** [comment]
LGTM

**Comment by vforge** [comment]
@nandy-andy Still looks ok

**Comment by nandy-andy** [comment]
Thanks @vforge we'll work on it a little bit longer since @PiotrGackowski found one tiny issue but soon it'll get merge, I believe :japanese_ogre:

**Pull request merged**
