### PR TITLE
MOB-1701

### PR DESCRIPTION
**Pull request by nandy-andy**
This is a refactoring done after a quick fix of [P2 bug](https://wikia-inc.atlassian.net/browse/MOB-1141).

Added a hashmap of available filters, refactored code and removed unnecessary parameters passed to methods.

One crucial change is new memcached keys.

### CODE REVIEW

**Comment by wladekb** [comment]
@nandy-andy ping

**Comment by nandy-andy** [comment]
Code review changes addressed. All PHP Unit tests passes. @SebastianMarzjan back to you ;)

We need to decide whether it merge directly to dev or plan some incremental roll-out because we're introducing new memcached keys here...

**Comment by nandy-andy** [comment]
ping @SebastianMarzjan

**Comment by SebastianMarzjan** [comment]
Api tests pass too:
http://qa-s2.wikia-prod:8080/view/Wikia%20API/job/api-tests_sandbox/13/testReport/

At <1k reqs/h I don't believe we need an incremental rollout:
https://kibana.wikia-inc.com/#/dashboard/elasticsearch/MOB-1701

Good to go.

**Pull request merged**
