### PR TITLE
VE-2125: There is no need to use mw.loader.use anymore because mw.loader.using returns promise as well

### PR DESCRIPTION
**Pull request by inez**
This is related to my change from couple months ago, where I made mw.loader.using get callback but also return promise.

### CODE REVIEW

**Comment by inez** [comment]
DO NOT CR YET - still working on it

**Comment by wladekb** [comment]
@inez thanks for taking the time to clean it up!

**Comment by inez** [comment]
@wladekb It's good for the code review now. Thank you.

**Comment by wladekb** [comment]
@inez sorry for the late response, lgtm

**Pull request merged**
