### PR TITLE
DAT-2375 Fix XSS vulnerability

### PR DESCRIPTION
**Pull request by sebastianmarzjan**

### CODE REVIEW

**Comment by SebastianMarzjan** [comment]
@idradm

**Comment by Grunny** [comment]
What about these two places as well?:
* https://github.com/Wikia/app/blob/3f46c6cc70/extensions/wikia/NjordPrototype/templates/Njord_Index.php#L40
* https://github.com/Wikia/app/blob/3f46c6cc70/extensions/wikia/NjordPrototype/templates/Njord_Index.php#L74

**Comment by SebastianMarzjan** [comment]
Thanks @Grunny !

**Comment by Grunny** [comment]
:+1:

**Comment by wladekb** [comment]
@SebastianMarzjan @idradm ping

**Comment by idradm** [comment]
if tests are all right we should merge it

**Comment by SebastianMarzjan** [comment]
$ make phpunit
...
OK, but incomplete, skipped, or risky tests!
Tests: 2226, Assertions: 17723, Skipped: 5.

**Pull request merged**
