### PR TITLE
DEL-1 | Remove XBoxGamerCardTag extension

### PR DESCRIPTION
**Pull request by kvas-damian**
```
[stats]>select count(*) from city_used_tags where ct_kind = 'xboxcard';
+----------+
| count(*) |
+----------+
|        0 |
+----------+
1 row in set (1.29 sec)
```

https://github.com/Wikia/config/pull/2137

### CODE REVIEW

**Review by rybmat — APPROVED** [review]

**Review by hakubo — APPROVED** [review]

**Comment by macbre** [comment]
@kvas-damian, `xboxcard` is not defined in https://github.com/Wikia/backend/blob/master/bin/specials/tags_report.pl#L34 - hence the query returns no rows. But that does not mean it's not used across the site :)

**Comment by TK-999** [comment]
@kvas-damian Is this good to merge? 🙂

**Comment by macbre** [comment]
@kvas-damian / @hakubo - ping

**Comment by kvas-damian** [comment]
Without a proof that it's not used I don't feel comfortable with merging this PR.
Let's get back to it one more time and start with gathering real usage of this feature.

**Pull request closed without merging**
