### PR TITLE
ADEN-489 Switch Liftium 2013 based on wg or URL

### PR DESCRIPTION
**Pull request by gabrys**
$wgAdDriverUseLiftium2013=true or ?useliftium2013=1

This is another approach for #1512

### CODE REVIEW

**Comment by wladekb** [comment]
@gabrys ping

**Comment by wladekb** [comment]
@gabrys ping

**Comment by wladekb** [comment]
@gabrys ping, should this be considered invalid and closed?

**Comment by gabrys** [comment]
ping @nandy-andy

**Comment by nandy-andy** [comment]
The PR has conflicts, the ticket is closed as "old and forgotten" and Liftium is on live-support (we'd like to kill it ASAP). I'm closing this pull request :crying_cat_face:

**Pull request closed without merging**
