### PR TITLE
FAN-2139: Permissions for accessing WP admin interface

### PR DESCRIPTION
**Pull request by themech**
Related config change: https://github.com/Wikia/config/pull/2119

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L426](https://github.com/Wikia/app/blob/906a6d98534abbc56cfd34f2bf4a5c99c01cbecf/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L426): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L428](https://github.com/Wikia/app/blob/906a6d98534abbc56cfd34f2bf4a5c99c01cbecf/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L428): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L430](https://github.com/Wikia/app/blob/906a6d98534abbc56cfd34f2bf4a5c99c01cbecf/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L430): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L432](https://github.com/Wikia/app/blob/906a6d98534abbc56cfd34f2bf4a5c99c01cbecf/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L432): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L137](https://github.com/Wikia/app/blob/906a6d98534abbc56cfd34f2bf4a5c99c01cbecf/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L137): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L138](https://github.com/Wikia/app/blob/906a6d98534abbc56cfd34f2bf4a5c99c01cbecf/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L138): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L165](https://github.com/Wikia/app/blob/906a6d98534abbc56cfd34f2bf4a5c99c01cbecf/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L165): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L426](https://github.com/Wikia/app/blob/6c9344c4b5a73397ed0bec0fb192f4b8b78a2f66/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L426): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L428](https://github.com/Wikia/app/blob/6c9344c4b5a73397ed0bec0fb192f4b8b78a2f66/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L428): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L430](https://github.com/Wikia/app/blob/6c9344c4b5a73397ed0bec0fb192f4b8b78a2f66/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L430): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L432](https://github.com/Wikia/app/blob/6c9344c4b5a73397ed0bec0fb192f4b8b78a2f66/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L432): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L137](https://github.com/Wikia/app/blob/6c9344c4b5a73397ed0bec0fb192f4b8b78a2f66/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L137): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L138](https://github.com/Wikia/app/blob/6c9344c4b5a73397ed0bec0fb192f4b8b78a2f66/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L138): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L165](https://github.com/Wikia/app/blob/6c9344c4b5a73397ed0bec0fb192f4b8b78a2f66/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L165): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L426](https://github.com/Wikia/app/blob/1abc0a9c6e76e72d8fcc50ec8302dda096d9f9e1/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L426): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L428](https://github.com/Wikia/app/blob/1abc0a9c6e76e72d8fcc50ec8302dda096d9f9e1/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L428): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L430](https://github.com/Wikia/app/blob/1abc0a9c6e76e72d8fcc50ec8302dda096d9f9e1/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L430): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L432](https://github.com/Wikia/app/blob/1abc0a9c6e76e72d8fcc50ec8302dda096d9f9e1/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L432): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L137](https://github.com/Wikia/app/blob/1abc0a9c6e76e72d8fcc50ec8302dda096d9f9e1/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L137): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L138](https://github.com/Wikia/app/blob/1abc0a9c6e76e72d8fcc50ec8302dda096d9f9e1/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L138): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L165](https://github.com/Wikia/app/blob/1abc0a9c6e76e72d8fcc50ec8302dda096d9f9e1/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L165): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by WikiaTech** [comment]
SonarQube analysis reported 7 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L426](https://github.com/Wikia/app/blob/bc09cfbe06dba61dab5646133ad5a56b343e9d7e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L426): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L428](https://github.com/Wikia/app/blob/bc09cfbe06dba61dab5646133ad5a56b343e9d7e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L428): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L430](https://github.com/Wikia/app/blob/bc09cfbe06dba61dab5646133ad5a56b343e9d7e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L430): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![MAJOR][MAJOR] [PermissionsConfigurationImpl.php#L432](https://github.com/Wikia/app/blob/bc09cfbe06dba61dab5646133ad5a56b343e9d7e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L432): Add curly braces around the nested statement(s). [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS121)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L137](https://github.com/Wikia/app/blob/bc09cfbe06dba61dab5646133ad5a56b343e9d7e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L137): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L138](https://github.com/Wikia/app/blob/bc09cfbe06dba61dab5646133ad5a56b343e9d7e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L138): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)
1. ![INFO][INFO] [PermissionsConfigurationImpl.php#L165](https://github.com/Wikia/app/blob/bc09cfbe06dba61dab5646133ad5a56b343e9d7e/lib/Wikia/src/Service/User/Permissions/PermissionsConfigurationImpl.php#L165): Move this trailing comment on the previous empty line. [rule](https://sonarqube.wikia-inc.com/coding_rules#rule_key=php%3AS139)

[INFO]: https://sonarsource.github.io/sonar-github/severity-info.png 'Severity: INFO'
[MAJOR]: https://sonarsource.github.io/sonar-github/severity-major.png 'Severity: MAJOR'

**Comment by mklucsarits** [comment]
LGTM

**Pull request merged**
