### PR TITLE
SOC-181 | AjaxLogin removal

### PR DESCRIPTION
**Pull request by kvas-damian**
Removed extension + all dependencies on it's code.

Don't merge without config branch.

### CODE REVIEW

**Comment by macbre** [comment]
Finally! Tusen takk :)

**Comment by bkoval** [comment]
LGTM :red_circle:

**Comment by rafalkalinski** [comment]
LGTM
Our system it a little better place right now :)

**Comment by macbre** [comment]
Guys, you've just made the world a little bit better place to live!

**Pull request merged**
