### PR TITLE
VOLDEV-20: fix $wgAllowCopyUploads

### PR DESCRIPTION
**Pull request by Monchoman45**
@Grunny 

This is old but should still work. Needs to be pushed upstream too, but currently [no one owns MultiUpload](https://www.mediawiki.org/wiki/Extension:MultiUpload), so I don't know how to go about that.

### CODE REVIEW

**Comment by dianafa** [comment]
Is this PR/ this LGTM still valid? :) @Monchoman45 @onei

**Comment by onei** [comment]
@dianafa It needs rebasing to verify it works currently (due to changes in LocalSettings.php), but it did indeed work back then.

**Comment by onei** [comment]
@dianafa verified via https://github.com/Wikia/app/compare/dev...WikiaVolDev:VOLDEV-20-2 this does indeed still work. Rebasing this went horribly wrong for me, hence the new branch.

**Comment by dianafa** [comment]
cool, can we close this PR then? :)

**Comment by Monchoman45** [comment]
Yea, still WFM.

**Pull request merged**
