### PR TITLE
Some checks fore video description edit

### PR DESCRIPTION
**Pull request by shaedrich**

### CODE REVIEW

**Comment by mszabo-wikia** [comment]
Thank you for your contribution! Please note that in accordance with the [Pull Request Policy](http://dev.wikia.com/wiki/Volunteer_Developers/Pull_Request_Policy), we can only accept contributions which provide a fix for a known issue that has been reported to us and registered in our bug tracking system.

**Comment by shaedrich** [comment]
@TK-999 If I report it, Eva will respond, that this is currently not in focus of development. So this to come to nothing, will it?

How can I sucessfully propose implementing these changes soon?

**Comment by mszabo-wikia** [comment]
>If I report it, Eva will respond, that this is currently not in focus of development. So this to come to nothing, will it?

This isn't an user-facing issue with the component.

**Comment by shaedrich** [comment]
Will this just be forfeited and that's it? No chance to probably acknowledge, it's needed anyway?

**Comment by mszabo-wikia** [comment]
It is a question of project management. It is not possible to deal with a diverse codebase consisting of over 3 million lines of code spread across 16,000+ files without bug triage. Rapid context switching triggered by code changes which do not pertain to issues prioritized for work is neither feasible nor desirable.

**Comment by shaedrich** [comment]
My feedback to FANDOM's project manangement, I have to discuss with Bert, haven't I? I can understand your situation, but your tests are setup for trouble-free continious deployment. Code review after sucessful tests is faster than fixing something on it's own.

**Comment by mszabo-wikia** [comment]
The existing test coverage is not sufficient for "trouble-free continuous deployment." External pull requests that do not pertain to existing tickets in the bug tracking system require a disproportionate amount of engineering time to verify and merge. It is for this reason that the Pull Request Policy was created—to facilitate external contributions without impeding development.

Project management is not within Community Support's responsibility.

**Comment by shaedrich** [comment]
So to who do I have to talk about that?

Where is the possibility to properly contribute?

**Comment by mszabo-wikia** [comment]
Contributions are welcome if they abide by our Pull Request Policy.

**Comment by shaedrich** [comment]
We go round in circles. Eva wont open a ticket. So which way should pursued instead?

**Comment by mszabo-wikia** [comment]
I am not aware of changes being considered to the policy at the moment. Unless that happens, new contributions must abide by it.

**Comment by shaedrich** [comment]
I do not challenge the policy but rather the project management. So how is the person in charge for that department?

**Comment by mszabo-wikia** [comment]
We don’t make management contact information available to the public and our policies and procedures are not open for debate.

**Comment by shaedrich** [comment]
We go round in circles again and again. No offence. I don't criticize you personally. You are just doing your work and that's okay. But if FANDOM abide by these concept and does not discuss with and listen to the users opinion and needs there's nothing more which have faith in the FANDOM community (FANDOM seems to work for it's own only and does not care about its users) and don't let me stay anymore.

I talked to Eva, Bert and now you and there was no unfailingly way to contribute. There are so much barriers and no way to take part in this concept as user (which is an important part in a living community).

**Pull request closed without merging**
