### PR TITLE
SOC-261 Restore support for XFBML plugin code

### PR DESCRIPTION
**Pull request by jsutterfield**
This ticket restores support for a set of Facebook social plugins which were lost when we migrated to the new SDK. The list of supported plugins is now: facepile, follow, like-box, like, recommendations, and share-button. More information: https://developers.facebook.com/docs/plugins

Ticket: https://wikia-inc.atlassian.net/browse/SOC-261

### CODE REVIEW

**Comment by kvas-damian** [comment]
LGTM

**Comment by jsutterfield** [comment]
@lizlux before you merge this, @kvas-damian brought up the point that the unit tests for this ticket may not be needed. The test doesn't actually test any functionality, it's just ensuring that certain values are part of that array. My thinking was that it would be a way to prevent people from removing those values again, but it's not the kind of thing that a unit test usually covers, nor is it very likely happen if not deliberately b/c we want to remove support for one of those plugins.

Thoughts on if we should keep the test or not?

**Comment by armonr** [comment]
I think it is good to keep, but ultimately, we need selenium tests for this :)

**Comment by lizlux** [comment]
Agreed that the test isn't very useful. It just adds work for whoever wants to edit that list, and I can't see why anyone would edit that list without a business reason. Also, it's not asserting that the list does *not* contain other values, so the list could become out of date without anyone realizing. 

+1 for TDD though!

**Comment by jsutterfield** [comment]
Fair enough, going to remove it. +1 on the selenium test though @armonr, I think that's the way to go here :)

**Pull request merged**
