### PR TITLE
VOLDEV-100 Added usergroup labels for Listusers

### PR DESCRIPTION
**Pull request by natewatson999**
This is in regards to VOLDEV-100 . The instructions say to tag @Grunny in this.

### CODE REVIEW

**Comment by Grunny** [comment]
@natewatson999 looks good, but for checkboxes, it's better to wrap the checkbox in the label tags as opposed to just using `for`. The [reason](http://stackoverflow.com/a/6293626) is that there isn't a gap between the checkbox and label text that when clicked won't (un)check the checkbox.

**Comment by natewatson999** [comment]
I will make an updated version then.

**Comment by natewatson999** [comment]
I changed the code to match. Do I make a new request, or do I keep the old
one?

**Comment by Grunny** [comment]
Nope, just pushing the additional change to the same branch will update the current PR. :)

**Comment by Grunny** [comment]
LGTM.

**Pull request merged**
