### PR TITLE
SUS-3869 remove SiteMapPage extension

### PR DESCRIPTION
**Pull request by sqreek**
https://wikia-inc.atlassian.net/browse/SUS-3869

@Wikia/sus

### CODE REVIEW

**Review by mszabo-wikia — APPROVED** [review]

**Comment by mszabo-wikia** [comment]
Let's clean up config and WF too

**Comment by kvas-damian** [comment]
To my best knowledge, we still link to these pages from the footer.
global sitemap fandom fandom powered by wikia chromium_272

**Review by kvas-damian — CHANGES_REQUESTED** [review]
Please make sure we don't link to this page before we disable it.

**Comment by sqreek** [comment]
Thanks for catching that @kvas-damian

**Comment by kvas-damian** [comment]
I believe you should remove the link in a separate release to avoid problems with cached API response for mobile-wiki and not existing page on Oasis.

**Comment by sqreek** [comment]
yes, for now I'm putting it here and wait for green light from @afadool

**Pull request closed without merging**
