### PR TITLE
remove hacks folder

### PR DESCRIPTION
**Pull request by hakubo**
Those should be kept inside forks or branches
we should not use hacks
and if we want to productise them
we should have moved them to proper place a while ago

@Wikia/engineers anyone against? Last call :) I will be merging this on Monday.

### CODE REVIEW

**Comment by pawelchcki** [comment]
:heart:

**Comment by gabrys** [comment]
Stop removing OUR codez! People really tried hard and produced 
interesting stuff here and you're just flushing it down the toilet!

**Comment by macbre** [comment]
Going to remove some hacks' leftovers from AssetsManager config:

```
Linting /usr/wikia/source/wiki/extensions/wikia/AssetsManager/config.php...
1662: extensions/wikia/hacks/ImageDrop/js/ImageDrop.js can not be found
        '//extensions/wikia/hacks/ImageDrop/js/ImageDrop.js',
1699: extensions/wikia/hacks/WikiMap/js/d3.v2.js can not be found
        '//extensions/wikia/hacks/WikiMap/js/d3.v2.js',
1700: extensions/wikia/hacks/WikiMap/js/jquery.xcolor.js can not be found
        '//extensions/wikia/hacks/WikiMap/js/jquery.xcolor.js',
1701: extensions/wikia/hacks/WikiMap/js/WikiMapIndexContent.js can not be found
        '//extensions/wikia/hacks/WikiMap/js/WikiMapIndexContent.js'
```

**Comment by pawelchcki** [comment]
:+1:

**Comment by vforge** [comment]
awesome, thanks @macbre !

**Pull request merged**
