### PR TITLE
VOLDEV-83: Fix confusing avatar file upload interface

### PR DESCRIPTION
**Pull request by mszabo-wikia**
This removes the default browser-specific UI which confuses users—a button can be used instead.
[VOLDEV-83](https://wikia-inc.atlassian.net/browse/VOLDEV-83)
@Grunny

### CODE REVIEW

**Comment by mszabo-wikia** [comment]
@kvas-damian @bkoval pinging you as UserProfilePageV3 top contributors

**Comment by kvas-damian** [comment]
LGTM

**Comment by bkoval** [comment]
LGTM :+1:

**Comment by kvas-damian** [comment]
@Grunny who is responsible for QA?

**Comment by Grunny** [comment]
@kvas-damian It depends on the scope of the changes. In general, it should be the team who owns the code, but we understand that teams may not have QA resources free to do so a lot of the time. So, for smaller changes like this I usually do some of the QA, with the reporter (i.e. ComSup/Kirkburn in this case) verifying the fix on preview as well. Let me know what your team prefers in this case.

**Comment by kvas-damian** [comment]
@qaga is on vacation so I verified in on my devbox. It'd great if someone could doublecheck on preview.

**Comment by mszabo-wikia** [comment]
Thanks guys! :cake:

**Pull request merged**
