### PR TITLE
CONCF-420 small design fixes in global footer and breakpoints

### PR DESCRIPTION
**Pull request by bognix**

### CODE REVIEW

**Comment by bognix** [comment]
ping @Warkot @dianafa

**Comment by rogatty** [comment]
LGTM

**Comment by dianafa** [comment]
LGTM

**Comment by Warkot** [comment]
Are those two variables that you changed (or maybe even more) linked somehow? If yes, maybe it would be a good idea to reflect that relationship in the code with something like `margin: 40px 0 $padding-width-large - 10px 0;`?

**Comment by bognix** [comment]
@Warkot - no they are not. One is the margin below the footer, seconds is spacing on the sides of an article.

**Comment by Warkot** [comment]
Then LGTM. :chicken:

**Pull request merged**
