### PR TITLE
PLATFORM-1725 Division by zero in imageServing.class

### PR DESCRIPTION
**Pull request by RafalWilinski**
Simple prevention of dividing by zero. Should not cause the same issue that `max(1, proportion['w'])` caused (-1 was used for keeping original aspect ratio).

### CODE REVIEW

**Comment by macbre** [comment]
Can we add unit tests here? :)

**Comment by RafalWilinski** [comment]
Sure, I was also thinking about it.

**Comment by RafalWilinski** [comment]
ping @macbre

**Comment by macbre** [comment]
:+1:

**Pull request merged**
