### PR TITLE
PLATFORM-1727: More extensive query logging

### PR DESCRIPTION
**Pull request by wladekb**
Based on the recent issues with core MediaWiki tables integrity I added more details logging of all write operations touching those table. This should help us with figuring out what happened in the future.

https://wikia-inc.atlassian.net/browse/PLATFORM-1727

/cc @macbre @owend @Grunny

### CODE REVIEW

**Comment by wladekb** [comment]
ping @macbre @owend @Grunny

**Comment by macbre** [comment]
Let's log the "forced" queries as a different message to avoid skewing stats.

Apart from that, Late Looks Good To Me

**Comment by Grunny** [comment]
:+1:

**Comment by owend** [comment]
LGTM 3

**Comment by wladekb** [comment]
This change needs adjustment pointed out by macbre.

**Comment by owend** [comment]
Ack, sorry.  Read too fast and the change itself was fine.

**Pull request merged**
