### PR TITLE
INT-124: Adding message string for mobile wikia-in-your-lang

### PR DESCRIPTION
**Pull request by mari-mcmurtrie**
We have to display different text for wikia-in-your-lang in mobile. Hence, adding text for mobile to the existing architecture.

### CODE REVIEW

**Comment by mari-mcmurtrie** [comment]
@lizlux When you have time, please take a look. Thank you.

**Comment by lizlux** [comment]
I was envisioning a separate API resource for mobile vs desktop, but this is probably fine. Pinging @gbenson-wikia for philosophical input.

**Comment by xaroth8088** [comment]
For the time being, this feels like the right approach to me.  Closer to the end of the year we hope to tackle i18n management more comprehensively, so as long as new strings are added to existing translation methods (i.e. no new methods for getting translated string bundles are added), we should be in good shape from that perspective.

**Comment by gbenson-wikia** [comment]
For the time being, this feels like the right approach to me.  Closer to the end of the year we hope to tackle i18n management more comprehensively, so as long as new strings are added to existing translation methods (i.e. no new methods for getting translated string bundles are added), we should be in good shape from that perspective.

(Sorry - was logged into my personal account for my previous comment)

**Comment by lizlux** [comment]
Cool, thanks @gbenson-wikia!

**Pull request merged**
