### PR TITLE
MAIN-7998 | removed redundant optimizely tracking

### PR DESCRIPTION
**Pull request by d34th4ck3r**
@macbre @perjg @justnpT

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 4 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [experiments-tracker.js#L13](https://github.com/Wikia/app/blob/3fe58d1c6f656c9829d6476d4ff0122fa75fab8f/extensions/wikia/SpitfiresContributionExperiments/scripts/experiments-tracker.js#L13): Remove the declaration of the unused 'freshlyRegisteredExperimentId' variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AUnusedVariable)
1. MAJOR [experiments-tracker.js#L13](https://github.com/Wikia/app/blob/3fe58d1c6f656c9829d6476d4ff0122fa75fab8f/extensions/wikia/SpitfiresContributionExperiments/scripts/experiments-tracker.js#L13): Remove this useless assignment to local variable "freshlyRegisteredExperimentId" [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
1. MAJOR [experiments-tracker.js#L14](https://github.com/Wikia/app/blob/3fe58d1c6f656c9829d6476d4ff0122fa75fab8f/extensions/wikia/SpitfiresContributionExperiments/scripts/experiments-tracker.js#L14): Remove the declaration of the unused 'usersWithoutEditExperimentId' variable. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AUnusedVariable)
1. MAJOR [experiments-tracker.js#L14](https://github.com/Wikia/app/blob/3fe58d1c6f656c9829d6476d4ff0122fa75fab8f/extensions/wikia/SpitfiresContributionExperiments/scripts/experiments-tracker.js#L14): Remove this useless assignment to local variable "usersWithoutEditExperimentId" [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)

**Comment by perjg** [comment]
@d34th4ck3r Won't this mess up the tracking label for any other Spitfires experiments that are currently running?

Is this fix possible instead?

`
	function getVariationName() {
		if (!window.optimizely || $.isEmptyObject(window.optimizely.variationNamesMap)) {
			return null;
		}

		if (window.optimizely.activeExperiments.indexOf(freshlyRegisteredExperimentId) !== -1) {
			return window.optimizely.variationNamesMap[freshlyRegisteredExperimentId].toLowerCase();
		}
		return window.optimizely.variationNamesMap[usersWithoutEditExperimentId].toLowerCase();
	}
`

**Comment by macbre** [comment]
I do not have enough context to review this change.

**Comment by perjg** [comment]
LGTM for the blocker fix, but please check with @lukaszkonieczny  if this is an ok long-term fix.

**Comment by Grunny** [comment]
LGTM as the blocker fix. A long-term fix shouldn't be needed as this was experimental code that isn't used in any other active experiments and should be cleaned up/removed at some point in the future.

**Comment by macbre** [comment]
@d34th4ck3r - can this one be merged?

**Comment by macbre** [comment]
@d34th4ck3r - please make sure this fix is included in the branch that will be released tomorrow.

**Pull request merged**
