### PR TITLE
ADEN-3901 Set tierNONE when there is no ad from Vulcan

### PR DESCRIPTION
**Pull request by fraszczakszymon**
Send new value to DFP in order to mark not responded Vulcan

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [rubiconVulcan.spec.js#L2](https://github.com/Wikia/app/blob/d90409bd658aa836836e80a59116bc7dd94acf87/extensions/wikia/AdEngine/js/spec/lookup/rubicon/rubiconVulcan.spec.js#L2): This function has 212 lines, which is greater than the 100 lines authorized. Split it into smaller functions. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS138)
1. MAJOR [rubiconVulcan.spec.js#L2](https://github.com/Wikia/app/blob/d90409bd658aa836836e80a59116bc7dd94acf87/extensions/wikia/AdEngine/js/spec/lookup/rubicon/rubiconVulcan.spec.js#L2): Function has a complexity of 26 which is greater than 10 authorized. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AFunctionComplexity)

**Comment by WikiaTech** [comment]
SonarQube analysis reported 2 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MAJOR [rubiconVulcan.spec.js#L2](https://github.com/Wikia/app/blob/a9166dcb49788bffc0d70e7c86dbeb6953899c4c/extensions/wikia/AdEngine/js/spec/lookup/rubicon/rubiconVulcan.spec.js#L2): This function has 225 lines, which is greater than the 100 lines authorized. Split it into smaller functions. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS138)
2. MAJOR [rubiconVulcan.spec.js#L2](https://github.com/Wikia/app/blob/a9166dcb49788bffc0d70e7c86dbeb6953899c4c/extensions/wikia/AdEngine/js/spec/lookup/rubicon/rubiconVulcan.spec.js#L2): Function has a complexity of 28 which is greater than 10 authorized. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AFunctionComplexity)

**Comment by drets** [comment]
LGTM :+1:

**Comment by bulaszenko** [comment]
Checked works good

**Pull request merged**
