### PR TITLE
CONCF-842 | Fix backgrounds for Safari 8

### PR DESCRIPTION
**Pull request by vforge**
/cc @bognix @nandy-andy @Warkot

### CODE REVIEW

**Comment by Warkot** [comment]
LGTM

**Comment by hakubo** [comment]
Seriously?
LGTM

**Comment by vforge** [comment]
@hakubo Yes. Apparently `::before` and `::after` inherits `background` property which overrides their `background-image`.

**Comment by rogatty** [comment]
LGTM

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
