### PR TITLE
SOC-256 Prevent from PHP fatal due to empty session

### PR DESCRIPTION
**Pull request by bkoval**
@kvas-damian @garthwebb Could you take a look? This should take care fo the fatal as @garthwebb suggested

### CODE REVIEW

**Comment by kvas-damian** [comment]
This change will handle fatal errors for sure. 
I'm thinking about fixing root cause, but don't have enough knowledge in this area. 
BTW: I'm curious why this code gets executed on tasks machine.

**Comment by bkoval** [comment]
http://qa-s2.wikia-prod:8080/job/unitTests_php_branches/11119/console - triggered Jenkins build manually and it passed :dancers:

**Comment by armonr** [comment]
@kvas-damian this call is part of the [FB SDK](https://github.com/Wikia/app/blob/dev/lib/composer/facebook/php-sdk-v4/src/Facebook/FacebookSignedRequestFromInputHelper.php#L92-92) which returns null if it cannot find/validate FB session cookie.

**Comment by armonr** [comment]
LGTM :+1:

**Comment by garthwebb** [comment]
@kvas-damian, Armon is correct and furthermore its ok if it cannot find or validate the FB session.  There are a few places where the code tries to get a session to see how it should proceed.  For example, it will try to load the session in order to look up a user/facebook mapping.  If its not found, we just prompt the user to connect.

**Comment by garthwebb** [comment]
LGTM!

**Comment by bkoval** [comment]
Thanks for feedback guys! I will close this one now and reopen targetting it at a correct sprint branch once it's created.

**Pull request closed without merging**
