### PR TITLE
HG-600: Add information about section indexes to WikiaMobile and ArticleAsJson output

### PR DESCRIPTION
**Pull request by inez**
Given the fact that WikiaMobile and ArticleAsJson are to be retired - and latter to be replaced by Article Service - this seems like a right solution

This change is also unifying output for ArticleAsJson so it does not depend on user state (logged in or out).

### CODE REVIEW

**Comment by owend** [comment]
Yep, this LGTM

**Comment by kenkouot** [comment]
This looks good to me too.

**Comment by inez** [comment]
@hakubo @kenkouot already merged it, but as the original plan was to have you review it as well - please take a look when you get a chance :) Thanks!

**Comment by hakubo** [comment]
LGTM

**Pull request merged**
