### PR TITLE
Concf 847 - send article ID in API response

### PR DESCRIPTION
**Pull request by bognix**
/cc @rogatty @hakubo @vforge 

related PR: https://github.com/Wikia/mercury/pull/1195

### CODE REVIEW

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by rogatty** [comment]
LGTM but can it break some API tests?
/cc @inez

**Comment by hakubo** [comment]
LGTM

**Comment by inez** [comment]
LGTM - however in this case I would add "id" to both videos and images (instead of only images) to keep the response more consistent.

@rogatty Currently we don't have tests for this API. We used to have them in VisualEditor-old but they were not migrated during upstream sync. It would be good to do it within next upstream sync - coming later this year.

**Pull request merged**
