### PR TITLE
DAT-2912 Support empty ParserOutput in ApiParse

### PR DESCRIPTION
**Pull request by sebastianmarzjan**
https://kibana.wikia-inc.com/index.html#/dashboard/elasticsearch/DAT-2912

### CODE REVIEW

**Comment by SebastianMarzjan** [comment]
cc @macbre

**Comment by macbre** [comment]
lgtm

**Comment by macbre** [comment]
lgtm

**Comment by inez** [comment]
How is this PR solving the real issue here? `$p_result` is not what code expects it to be but where the idea of setting it to `new ParserOutput('');` comes from?
Was it tested? Clearly after that change API is returning empty response instead of an error but it is still a wrong response.

**Comment by sebastianmarzjan** [comment]
It's an intermediate step (yeah, the comment would be great there) to identify cases in which it happens:
https://kibana.wikia-inc.com/index.html#/dashboard/elasticsearch/DAT-2912

Is your question related to https://wikia-inc.atlassian.net/browse/PLATFORM-1355 ?
What kind of information do you need?

**Pull request merged**
