### PR TITLE
Merging PR #8953 int release-344

### PR DESCRIPTION
**Pull request by drsnyder**
Merging PR #8953 into release-344 for Tuesday November 3rd. 

Blocked by the testing of #8961 on sandbox-s3. Once the test is complete and cleared then we can merge this one.

@Wikia/services-team

### CODE REVIEW

**Comment by ArturKlajnerok** [comment]
Lgtm :+1:

**Comment by macbre** [comment]
@drsnyder, please always deploy changes merged into preview branch. Otherwise, they are not covered by the pre-release test runs. Thanks!

**Comment by drsnyder** [comment]
> please always deploy changes merged into preview branch. Otherwise, they are not covered by the pre-release test runs. Thanks!

@macbre how do I do that?

**Comment by macbre** [comment]
```
dt prep / push -a wikia -e preview
```

**Comment by drsnyder** [comment]
Ah, ok got it.

**Comment by drsnyder** [comment]
So how do we trigger the automated tests? Do they happen periodically or are they triggered on push to preview?

**Pull request merged**
