### PR TITLE
ADEN-6608 Hide smart banner when BFAA is loaded

### PR DESCRIPTION
**Pull request by nandy-andy**
https://wikia-inc.atlassian.net/browse/ADEN-6608

Depends on: https://github.com/Wikia/mobile-wiki/pull/380

### CODE REVIEW

**Review by fraszczakszymon — APPROVED** [review]

**Comment by fraszczakszymon** [comment]
Please don't merge till https://github.com/Wikia/mobile-wiki/pull/380 is released

**Comment by nandy-andy** [comment]
Strange. The tests pass on my devbox and don't seem like connected to the changes :-( 
```
Time: 24.39 seconds, Memory: 174.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 4343, Assertions: 6778, Skipped: 19.
```
```
Time: 12.13 seconds, Memory: 112.00MB

OK (106 tests, 509 assertions)
```

I'm merged master and we'll see...

**Review by v3rth — APPROVED** [review]

**Comment by kvas-damian** [comment]
Please resolve conflicts

**Comment by nandy-andy** [comment]
Conflicts resolved :)

PHPUnit tests on devbox:
```
Time: 23.89 seconds, Memory: 174.00MB

OK, but incomplete, skipped, or risky tests!
Tests: 4343, Assertions: 6778, Skipped: 19.
```
```
Time: 11.93 seconds, Memory: 114.00MB

OK (107 tests, 510 assertions)
```

**Pull request merged**
