### PR TITLE
SOC-3082: remove $wgEnableDiscussionPostsCountInUserIdentityBox

### PR DESCRIPTION
**Pull request by kerriamber**
https://wikia-inc.atlassian.net/browse/SOC-3082

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 43 issues
* MAJOR 15 major
* MINOR 28 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. MAJOR [UserProfilePageController.class.php](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php): File "UserProfilePageController.class.php" has 1019 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS104)
1. MAJOR [UserProfilePageController.class.php#L6](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L6): Class "UserProfilePageController" has 26 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
1. MAJOR [UserProfilePageController.class.php#L61](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L61): Remove this commented out code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS125)
1. MAJOR [UserProfilePageController.class.php#L160](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L160): The Cyclomatic Complexity of this function "renderActionButton" is 29 which is greater than 20 authorized. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1541)
1. MAJOR [UserProfilePageController.class.php#L413](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L413): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)
1. MAJOR [UserProfilePageController.class.php#L688](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L688): Reduce the number of returns of this function 6, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)
1. MAJOR [UserProfilePageController.class.php#L691](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L691): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)
1. MAJOR [UserProfilePageController.class.php#L695](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L695): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)
1. MAJOR [UserProfilePageController.class.php#L699](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L699): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)
1. MAJOR [UserProfilePageController.class.php#L702](https://github.com/Wikia/app/blob/2f23785aee4222bb067f8596fd40af7d8f264317/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L702): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)

**Comment by jsutterfield** [comment]
Looks like your branch is out of date with dev. We also have the value [here](https://github.com/Wikia/app/blob/dev/extensions/wikia/Discussions/DiscussionsVarToggler.class.php#L10) which should be removed.

**Comment by jsutterfield** [comment]
Also, we should make sure to remove this from [the config](https://github.com/Wikia/config/blob/87b8229cbe9caf59496b7f99b2ef8d60fe17c9db/CommonSettings.php#L4341) as well.

**Comment by WikiaTech** [comment]
SonarQube analysis reported 43 issues
- MAJOR 15 major
- MINOR 28 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MAJOR [UserProfilePageController.class.php](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php): File "UserProfilePageController.class.php" has 1019 lines, which is greater than 1000 authorized. Split it into smaller files. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS104)
2. MAJOR [UserProfilePageController.class.php#L6](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L6): Class "UserProfilePageController" has 26 methods, which is greater than 20 authorized. Split it into smaller classes. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1448)
3. MAJOR [UserProfilePageController.class.php#L61](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L61): Remove this commented out code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS125)
4. MAJOR [UserProfilePageController.class.php#L160](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L160): The Cyclomatic Complexity of this function "renderActionButton" is 29 which is greater than 20 authorized. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1541)
5. MAJOR [UserProfilePageController.class.php#L413](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L413): Reduce the number of returns of this function 4, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)
6. MAJOR [UserProfilePageController.class.php#L688](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L688): Reduce the number of returns of this function 6, down to the maximum allowed 3. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1142)
7. MAJOR [UserProfilePageController.class.php#L691](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L691): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)
8. MAJOR [UserProfilePageController.class.php#L695](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L695): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)
9. MAJOR [UserProfilePageController.class.php#L699](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L699): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)
10. MAJOR [UserProfilePageController.class.php#L702](https://github.com/Wikia/app/blob/cc46984f92c0118530b746fb7dd8882641fde396/extensions/wikia/UserProfilePageV3/UserProfilePageController.class.php#L702): Remove the code after this "return". [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1763)

**Review by jsutterfield — APPROVED** [review]
LGTM!

**Pull request merged**
