### PR TITLE
ignore internal traffic when reporting incorrect Phalanx user IP

### PR DESCRIPTION
**Pull request by ghost**
https://wikia-inc.atlassian.net/browse/PLATFORM-1473

The vast majority of the log entries come from our internal health checks, etc. which makes them false positives.

@macbre

### CODE REVIEW

**Comment by macbre** [comment]
:+1:

**Comment by ghost** [comment]
Per our conversation, I'll reassess the list of IPs.

**Comment by ghost** [comment]
These ones can be safely ignored, I think: 
- `memcache-warm-s1` — 214843 events
- `mercury-s4` — 142774 events
- `monitor-s2` — 126012 events
- `mercury-s3` — 111689 events
- `monitor-r2` — 64442 events
- `border-http-s4` — 1196 events
- `api-test-s1` — 311 events
- `mercury-r4` — 87 events
- `mercury-r3` — 40 events
- `staging-s3` — 31 events
- `border-http-s5` — 21 events

**Comment by macbre** [comment]
Handled in #8884

**Pull request closed without merging**
