### PR TITLE
SUS-157 In Wall i18n change parameter number

### PR DESCRIPTION
**Pull request by sqreek**
https://wikia-inc.atlassian.net/browse/SUS-157

this is quick fix.
We can think about refactoring getNotificationMessage cause building params is too dynamic there.

first part (merging duplicated code) was done in https://github.com/Wikia/app/pull/9723

// cc @Wikia/sustaining-team

### CODE REVIEW

**Comment by kamilkoterba** [comment]
Per offline discussion. 
Unit tests for this would be a nice idea.

**Comment by ghost** [comment]
Agreed. Otherwise :+1:

**Comment by sqreek** [comment]
test are added in https://github.com/Wikia/app/pull/9734

**Comment by kamilkoterba** [comment]
:+1:

**Pull request merged**
