### PR TITLE
FOR UPDATE and LOCK IN SHARE MODE are not write queries

### PR DESCRIPTION
**Pull request by ghost**
@drozdo

### CODE REVIEW

**Comment by drozdo** [comment]
LGTM

**Comment by drozdo** [comment]
should be case insensitive

**Comment by drozdo** [comment]
LGTM

**Comment by macbre** [comment]
For future reference:

``` sql
SELECT  rev_id,rev_page,rev_text_id,rev_timestamp,rev_comment,rev_user_text,rev_user,rev_minor_edit,rev_deleted,rev_len,rev_parent_id,rev_sha1,page_namespace,page_title,page_id,page_latest,user_name  FROM `revision` INNER JOIN `page` ON ((page_id = rev_page)) LEFT JOIN `wikicities_c3`.`user` ON ((rev_user != 0) AND (user_id = rev_user))  WHERE page_namespace = '8' AND page_title = 'Wikia.css' AND (rev_id=page_latest)  LIMIT 1   FOR UPDATE
```

**Pull request merged**
