### PR TITLE
Universal analytics fix for ads (dimension 20 missing)

### PR DESCRIPTION
**Pull request by gabrys**
Looks like a stupid copy&paste error.

### CODE REVIEW

**Comment by nandy-andy** [comment]
LGTM

**Comment by nandy-andy** [comment]
@gabrys do you think it's still worth merging? Seems legit :japanese_ogre: Unfortunately units failed and I can't tell why...

**Comment by WikiaTech** [comment]
SonarQube analysis reported 6 issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MAJOR [universal_analytics.js#L7](https://github.com/Wikia/app/blob/3a18fbff5744df2635ed7c35239a6ce51464956a/extensions/wikia/AnalyticsEngine/js/universal_analytics.js#L7): Remove the unused function parameter "undefined". [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AUnusedFunctionArgument)
2. MAJOR [universal_analytics.js#L277](https://github.com/Wikia/app/blob/3a18fbff5744df2635ed7c35239a6ce51464956a/extensions/wikia/AnalyticsEngine/js/universal_analytics.js#L277): Remove this useless assignment to local variable "markedSegments" [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1854)
3. MAJOR [universal_analytics.js#L377](https://github.com/Wikia/app/blob/3a18fbff5744df2635ed7c35239a6ce51464956a/extensions/wikia/AnalyticsEngine/js/universal_analytics.js#L377): Reduce the number of conditional operators (7) used in the expression (maximum allowed 3). [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AS1067)
4. MAJOR [universal_analytics.js#L417](https://github.com/Wikia/app/blob/3a18fbff5744df2635ed7c35239a6ce51464956a/extensions/wikia/AnalyticsEngine/js/universal_analytics.js#L417): Reduce the total number of "break" and "continue" statements in this loop to use one at most. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3ATooManyBreakOrContinueInLoop)
5. MAJOR [universal_analytics.js#L556](https://github.com/Wikia/app/blob/3a18fbff5744df2635ed7c35239a6ce51464956a/extensions/wikia/AnalyticsEngine/js/universal_analytics.js#L556): Either remove or fill this block of code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AEmptyBlock)
6. MAJOR [universal_analytics.js#L582](https://github.com/Wikia/app/blob/3a18fbff5744df2635ed7c35239a6ce51464956a/extensions/wikia/AnalyticsEngine/js/universal_analytics.js#L582): Either remove or fill this block of code. [rule](http://10.8.74.32:9000/coding_rules#rule_key=javascript%3AEmptyBlock)

**Comment by nandy-andy** [comment]
After merging `dev` it passed. Feel free to merge @gabrys if you still think we need it :blush:

**Pull request merged**
