### PR TITLE
Swagger2

### PR DESCRIPTION
**Pull request by nmonterroso**
@Wikia/platform-team @SebastianMarzjan 
Removing the php-doc style swagger 1.1 annotations and replacing with swagger 2.0 json. This was done so we could use [swagger-codegen](https://github.com/swagger-api/swagger-codegen) to generate external clients to interact with the Nirvana API.

Also removed the swagger php library, since that only supports parsing swagger info via the php-doc style definitions. There was no swagger php parser I could find, so I wrote a pretty basic one that should fill our needs.

The user-facing page (/api/v1) should be unchanged, except for some bugs I found in the swagger definitions. 

Note that this change will require any future changes to our swagger definitions to be defined in `nirvana.json` and be in the swagger 2.0 format. The format should be pretty self-explanatory from the existing definitions.

### CODE REVIEW

**Comment by SebastianMarzjan** [comment]
:+1:

**Comment by SebastianMarzjan** [comment]
One thing that slightly bothers me is the size of JSON file that is a result of aggregating all of the APIs in it. That seems to be harder to maintain.
As I might be missing something, it'd be great to know what were the factors considered in choosing this approach over previously used separate files for each of the APIs.

Thanks!

**Comment by nmonterroso** [comment]
Yeah, that bothered me too. See [this SO question](http://stackoverflow.com/questions/26917188/how-to-break-swagger-2-0-json-file-into-multiple-modules) for more info. I tried using `$ref` to split files, which sort of worked, but that did not play well with the code generating tools. We'll have to wait until that part of Swagger 2 is more mature before doing that, but I agree it's something that should be done.

**Comment by SebastianMarzjan** [comment]
Thanks for the information @nmonterroso !

**Pull request merged**
