### PR TITLE
CONCF-218 | Move Mercury includes to DefaultSettings.php

### PR DESCRIPTION
**Pull request by vforge**
See https://github.com/Wikia/config/commit/5524021107396f21ac818a56a1301ad0fe7c96e5
ping @warkot @bogna @nandy-andy

### CODE REVIEW

**Comment by Warkot** [comment]
LGTM :shipit:

**Comment by bognix** [comment]
LGTM

**Comment by nandy-andy** [comment]
LGTM :+1:

**Comment by hakubo** [comment]
LGTM :)

**Pull request merged**
