### PR TITLE
CONCF-361 | Change margins for large breakpoint

### PR DESCRIPTION
**Pull request by vforge**
CR @warkot @bognix

### CODE REVIEW

**Comment by bognix** [comment]
LGTM

**Comment by Warkot** [comment]
LGTM, but check what's up with the failed tests. :shipit:

**Comment by Warkot** [comment]
`npm ERR! fetch failed https://registry.npmjs.org/numerizer/-/numerizer-0.0.2.tgz`
…
`The command "npm install" failed and exited with 1 during .`
:/

**Comment by vforge** [comment]
Yeah :|

**Pull request merged**
