### PR TITLE
JPN-415 Fix global user table references

### PR DESCRIPTION
**Pull request by kamilkoterba**
@adamkarminski's fix for: https://wikia-inc.atlassian.net/browse/JPN-481

@Wikia/spitfires @perjg @d34th4ck3r

### CODE REVIEW

**Comment by kamilkoterba** [comment]
LGTM

**Comment by perjg** [comment]
There are a couple of other places in the CommunityPageSpecialUsersModel that access the external db like so:

```
global $wgExternalSharedDB;
$db = wfGetDB( DB_SLAVE, [], $wgExternalSharedDB );
```

For the change made for this task, wfGetDB is called like so:

```
global $wgExternalSharedDB;
$db = wfGetDB( DB_SLAVE );
```

@Grunny Would changing the call to wfGetDB allow the explicit `$wgExternalSharedDB . '_' . $wgDBcluster . '.user'` call to be simplified?

**Comment by Grunny** [comment]
@perjg If you did that, then you'd still need to specify the local DB name for all the local tables being queried. On Wookieepedia `$db = wfGetDB( DB_SLAVE );` will return a DB connection for the `starwars` database, so if you want to join on the user table, you need to specify the wikicities database copy present on that cluster. If you did, `$db = wfGetDB( DB_SLAVE, $wgExternalSharedDB . '_' . $wgDBcluster . '.user' );` on Wookieepedia, it would return a connection using the `wikicities_c4` database, and you'd need to specify `starwars` when querying local DB data (i.e. `starwars.revision`). So, it wouldn't clean it up much. We may want to centralise some of this summarised data in the future in the datawarehouse, so this isn't needed.

**Comment by Grunny** [comment]
Testing LGTM.

**Pull request merged**
