### PR TITLE
Execute yuicompressor without the memory limit

### PR DESCRIPTION
**Pull request by macbre**
Fixes regression caused by #6127 

@michalroszka / @wladekb / @bognix

### CODE REVIEW

**Comment by bognix** [comment]
Maybe we should investigate if it is possible to drop yuicompressor just to make our lives simpler in the future.

**Comment by macbre** [comment]
True, currently YUI compressor is used for two AM packages only:

```php
$newContent = self::minifyJS( $this->mContent, ( $this->mOid == 'oasis_shared_js' || $this->mOid == 'rte' ) ? true : false );
```

**Comment by jcellary** [comment]
LGTM

**Comment by lizlux** [comment]
@macbre, this seems to have only fixed the problem temporarily.  I just started seeing the JS errors again on my devbox.

**Comment by macbre** [comment]
@lizlux, can you add more details here or file a ticket? Thanks

**Comment by lizlux** [comment]
@macbre I'll do that if I see it pop up again. Looks like it's okay for now. Thanks!

**Comment by macbre** [comment]
Great, thanks!

**Pull request merged**
