### PR TITLE
CAKE-1460: Removes MW-specific styling for MW+CP integration

### PR DESCRIPTION
**Pull request by gbenson-wikia**
Layout styling was left alone - this intentionally only addressed the colors.  There's some additional styling work that'll be required to get this polished up, but that's outside the scope of this ticket.

@Wikia/cake

### CODE REVIEW

**Comment by drsnyder** [comment]
Was there a commit that added these that you referenced to unwind them?

**Comment by nmonterroso** [comment]
LGTM

**Comment by gbenson-wikia** [comment]
@drsnyder The bake-off specific changes were scattered across a large enough number of commits that it was faster to do it this way than to try to unwind them individually.  Knowing that we're going to need to make a fit-and-finish pass anyway, I elected to skip anything structural and just strip out anything having to do with colors.  This let me test each color in small batches as I went, permitting me to ensure that the look-and-feel was still acceptable.

**Comment by drsnyder** [comment]
@gbenson-wikia ok, sounds good. I was cautious about giving a blanket "LGTM" since I wasn't familiar with the changes that were added previously.

**Pull request merged**
