### PR TITLE
Removing jserrorslog.wikia.com domain

### PR DESCRIPTION
**Pull request by ljagiello**
I would like to cleaned up VCL and chef-repo from `jserrorslog.wikia.com`. To do that I'm going to disable MW code responsible for generating requests with `jserrorslog.wikia.com` domain.

/cc @gabrys @macbre @owend

### CODE REVIEW

**Comment by owend** [comment]
This LGTM.  Would need to merge to release branch if you want it to go out tomorrow.

**Comment by macbre** [comment]
Let's remove the code bound to this hook as well.

**Comment by ljagiello** [comment]
@macbre sure, I'll create separate PR after we will know it's not in use.

**Comment by macbre** [comment]
:+1:

**Pull request merged**
