### PR TITLE
CONCF-162 | fallback for Mercury requests that reach MediaWiki set to WikiaMobile

### PR DESCRIPTION
**Pull request by Warkot**

### CODE REVIEW

**Comment by hakubo** [comment]
Looks like sensitive fallback lgtm

**Comment by rogatty** [comment]
LGTM

In QA it has to be checked separately with:
1. Query param `useskin=mercury`
2. Header `'X-Skin': 'mercury'`

**Comment by Warkot** [comment]
I'd add `useskin=mercury` cookie to this list.

**Comment by Warkot** [comment]
I'd add `useskin=*` cookie to this list.

**Comment by Warkot** [comment]
Sry, commenting from mobile.

**Comment by tomasznapieralski** [comment]
LGTM

**Pull request merged**
