### PR TITLE
SUS-170: Remove support for adding (or swapping) videos from Metacafe

### PR DESCRIPTION
**Pull request by inez**
Practically we are already not supporting Metacafe - we just fail badly when someone tries to embed Metacafe video.

### CODE REVIEW

**Comment by inez** [comment]
@Wikia/sustaining-team @owend

**Comment by owend** [comment]
I think we can also remove all 'vet-metacafe' keys from VideoEmbedTool.i18n :recycle: 

https://github.com/Wikia/app/blob/dev/extensions/wikia/VideoEmbedTool/VideoEmbedTool.i18n.php#L176

**Comment by ghost** [comment]
Agreed. Please, clean up the relevant i18n files and let's move it to QA. :-)

**Comment by inez** [comment]
This is ready for CR again. @owend after you CR please let me know so I move it to QA in JIRA.

**Comment by owend** [comment]
LGTM.  Nice shade of red on this PR.  :)

**Pull request merged**
