### PR TITLE
CONCF-641 | remove Special:Mercury

### PR DESCRIPTION
**Pull request by tomasznapieralski**
https://wikia-inc.atlassian.net/browse/CONCF-641

### CODE REVIEW

**Comment by bognix** [comment]
what about this: https://github.com/Wikia/app/blob/c9d5121db1124a06315fa02e2c82d4203846d2f5/extensions/wikia/SkinChooser/SkinChooser.class.php#L212 ? can't we remove this check?

**Comment by rogatty** [comment]
Yeah, please grep the app repo for `mercury` string, it might somewhere else too. GL&HF!

**Comment by rogatty** [comment]
Also PR title doesn't reflect code changes at all.

**Comment by vforge** [comment]
@bognix @rogatty We aren't changing behaviour of current `useskin=mercury` . We're just defaulting `useskin=wikiamobile` to work exaclty the same as `useskin=mercury` - see https://github.com/Wikia/wikia-vcl/pull/552

Removal of opt-in is an additional work in order to remove Mercury from the user's perspective as it's enabled by default now.

**Comment by bognix** [comment]
OK. Please ping Dima: https://github.com/Wikia/selenium-tests/search?utf8=%E2%9C%93&q=wikiamobile

**Comment by rogatty** [comment]
If this stays as is then please rename the PR. I see only the removing of `SpecialMercuryPage` here.

**Comment by vforge** [comment]
@tomasznapieralski I agree with @rogatty on this one - please consider renaming the ticket

**Comment by bognix** [comment]
LGTM

**Comment by rogatty** [comment]
LGTM

**Comment by hakubo** [comment]
LGTM

**Pull request merged**
