### PR TITLE
CONCF-41 remove never assigned variable

### PR DESCRIPTION
**Pull request by bognix**
I removed $useRDFData variable which was never assigned and $timer variable which was never used.
$useRDFData variable is causing PHP Erros.
@lizlux you removed the assignment in https://github.com/Wikia/app/commit/64643127112194a59f2e51c3e7a6609edec31543 - is it OK if I remove the rest?

### CODE REVIEW

**Comment by vforge** [comment]
LGTM

**Comment by macbre** [comment]
:+1:

**Comment by lizlux** [comment]
Thanks for looking into this @bognix. My only concern is that we added the RDF data to thumbnails in order to increase SEO. I don't remember the full context of why I removed it, but it's possible that I did it by accident, and that the actual fix is to put it back in place. @shareif would have more info on this than me. Please check in with him to see if the we should reinstate RDF data in the thumbnail HTML. Thanks!

**Comment by shareif** [comment]
Yeah, it looks like something fairly important for Video SEO.

**Comment by bognix** [comment]
Ok, I'll bring back the variable assignment.

**Comment by bognix** [comment]
This change is only affecting wikiamobile skin.

**Comment by vforge** [comment]
LGTM

**Comment by hakubo** [comment]
LGTM

**Comment by lizlux** [comment]
Ah okay, I looked at the code more and it does in fact only affect WikiaMobile. It would be nice to adjust the code to reflect that better, but this is probably fine for now.

**Pull request merged**
