### PR TITLE
Update .editorconfig for PHP and SCSS configuration

### PR DESCRIPTION
**Pull request by vforge**
/cc @bognix @Warkot @hakubo

### CODE REVIEW

**Comment by Warkot** [comment]
Awesome stuff. :+1: Is it possible to add other [guidelines](https://github.com/Wikia/guidelines) here like where to put spaces, when to break line, to use `[]` array constructor instead of `array()` in PHP?

**Comment by vforge** [comment]
Unfortunately, nope - only basic file structure - https://github.com/editorconfig/editorconfig/wiki/EditorConfig-Properties

**Comment by Warkot** [comment]
What about `trim_trailing_whitespace = true`?

**Comment by bognix** [comment]
AWESOME! LGTM!

**Comment by vforge** [comment]
@Warkot I don't want to trim multiline text blocks for now - let's leave it and re-iterate if needed.

**Comment by Warkot** [comment]
Sure, @vforge, great job! LGTM :+1:

**Pull request merged**
