### PR TITLE
FAN-1047 removing vertical links for non-en on fandom

### PR DESCRIPTION
**Pull request by lizlux**
Pointing this PR to the main x-wing branch since we're going off of this one now. 

This removes the games/movies/tv links for non-en pages. 

@Wikia/x-wing @Wikia/west-wing

### CODE REVIEW

**Comment by WikiaTech** [comment]
SonarQube analysis reported 13 issues
- MINOR 13 minor

#### Top 10 extra issues

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:
1. MINOR [DesignSystemGlobalNavigationModel.class.php#L5](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L5): Define a constant instead of duplicating this literal "wikis" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
2. MINOR [DesignSystemGlobalNavigationModel.class.php#L32](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L32): Define a constant instead of duplicating this literal "header" 6 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
3. MINOR [DesignSystemGlobalNavigationModel.class.php#L35](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L35): Define a constant instead of duplicating this literal "image" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
4. MINOR [DesignSystemGlobalNavigationModel.class.php#L36](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L36): Define a constant instead of duplicating this literal "title" 18 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
5. MINOR [DesignSystemGlobalNavigationModel.class.php#L38](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L38): Define a constant instead of duplicating this literal "value" 3 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
6. MINOR [DesignSystemGlobalNavigationModel.class.php#L47](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L47): Define a constant instead of duplicating this literal "link-text" 8 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
7. MINOR [DesignSystemGlobalNavigationModel.class.php#L49](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L49): Define a constant instead of duplicating this literal "translatable-text" 21 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
8. MINOR [DesignSystemGlobalNavigationModel.class.php#L67](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L67): Define a constant instead of duplicating this literal "links" 5 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
9. MINOR [DesignSystemGlobalNavigationModel.class.php#L130](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L130): Define a constant instead of duplicating this literal "Search" 4 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)
10. MINOR [DesignSystemGlobalNavigationModel.class.php#L139](https://github.com/Wikia/app/blob/ba5cbbe99b7fa98021e6cf24163735a0ce43b724/includes/wikia/models/DesignSystemGlobalNavigationModel.class.php#L139): Define a constant instead of duplicating this literal "param-name" 5 times. [rule](http://10.8.74.32:9000/coding_rules#rule_key=php%3AS1192)

**Comment by lizlux** [comment]
Looks like API tests are failing on XW-1966, which is what I based this branch off of, so I'm assuming it's not an issue with this new code. 

```
FAIL: test_footer_en (apitests.DesignSystem.test_footer.Footer_ApiV1Custom)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/liz_lux/PycharmProjects/api-tests/apitests/wikia.py", line 427, in wrapped_f
    f(cls, *args)
  File "/Users/liz_lux/PycharmProjects/api-tests/apitests/DesignSystem/test_footer.py", line 10, in test_footer_en
    self.assertEqual(len(response), 11)
AssertionError: 10 != 11
```

**Comment by mklucsarits** [comment]
This doesn't change the Fandom logo link to Explore for international users. Will that be done later or another way?

**Comment by lizlux** [comment]
Oops, forgot the logo link. Thanks @mklucsarits I'll fix that.

**Comment by mklucsarits** [comment]
LGTM. The logo link update will be handled by X-Wing team.

**Pull request merged**
